### ISSUE TITLE
updateStateWithLinkAt not working properly

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#101]
Calling updateStateWithLinkAt(link_name), being link_name the end-effector parent link, brings all the links to the expected pose, with the exception of the one following link_name (the palm in this case), that appears shifted. Removing the call to updateGivenGlobalLinkTransform() at the end of the method solves the problem, but probably breaks something else ;)

**Comment by isucan** [comment]
I am not sure I can replicate this problem, but I refactored your code a bit. Can you send a print screen?

**Comment by marioprats** [comment]
I probably did something wrong. Seems to work now with you refactoring. I saw you also added a reachability button. That was next in my todo list, so thanks a lot!!
