### ISSUE TITLE
incorrect display of axes

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#102]
If I load a few poses, then disable the MotionPlanning plugin, and re-enable it, the axes look all weird.
They are much larger than they should be and appear displayed even if the show x/y/z checkboxes are disabled

**Comment by marioprats** [comment]
Fixed in dd8373d65983737e2f84b436e65be91fcb0aa465
Sorry, my idea was to send a pull request, but after the change in the repository names I had a bad configuration in my system and pushed it to the upstream repo. Fortunately it's only three lines ;)
