### ISSUE TITLE
Error: stack/package not found

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#103]
When starting move_group_action_server using the move_group.launch file generated by the Setup Assistant, I get a lot of error messages that say:

```
[rospack] Error: stack/package planning not found
[librospack]: error while executing command
```

I'm not sure if its causing problems with other things or not; move_group does still launch.

**Comment by davetcoleman** [comment]
On further thought, this is probably because rospack hasn't been properly converted to work with catkin and the relaxed requirement that packages no longer need to have their folder name the same as their package name. @dirk-thomas

**Comment by isucan** [comment]
I think @mirzashah fixed this

**Comment by mirzashah** [comment]
I am not aware of this problem nor did I fix it. However, rospack should work with catkin. This was something @dirk-thomas did a long while back.

**Comment by davetcoleman** [comment]
i just updated and rebuilt all of moveit, and updated all my ros debians, but i'm still getting the error. my console output is [here](https://gist.github.com/4323039)

**Comment by dirk-thomas** [comment]
Does any of your launch files looks for a former stack / now metapackage? Those do not get installed (i.e. planning, ros). Probably you just need to point to a specific package instead?

If you can come up with a simple small example I can give it a shot - but the above mentioned setup has lots and lots of packages...

**Comment by isucan** [comment]
@mirzashah move_group loads a bunch of plugins, and all of them are in locations that do not match with the folder name. I thought Dave posted another bug about this. I thought this was the same issue. Is it not?

**Comment by mirzashah** [comment]
@isucan Yes there was a different issue regarding pluginlib, this sounds like something different.

See
https://github.com/ros/pluginlib/issues/6

**Comment by davetcoleman** [comment]
Can @isucan or someone confirm their moveit launch files are having similar error output so that we can rule out it is not just my setup? i think this is a related issue, but the previous Issue was in reference to the error output:

```
ERROR ros.rviz: Could not find package manifest (neither package.xml or deprectated manifest.xml) at same directory level as the plugin XML file /home/dave/ros/moveit/src/moveit_ros/visualization/planning_scene_rviz_plugin_description.xml. Plugins will likely not be exported properly.
)
```

**Comment by mirzashah** [comment]
I don't think they are related...the plugin issue was happening within pluginlib and had nothing to do with rospack. This is outside the scope of pluginlib and seems to be a rospack issue. If @isucan is experiencing the problem as well, I recommend overlaying rospack and finding out where it seems to be failing. Dirk is super overloaded so I can lend a helping hand if you guys can help me get setup with a moveit overlay.

**Comment by isucan** [comment]
I am experiencing the problem as well, yes.
Mirza, I can help you set up the env we use.

**Comment by dirk-thomas** [comment]
Confirmed to work with pluginlib 0.9.13.
