### ISSUE TITLE
Ability to connect to monitored planning scene (physical robot status)

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#104]
There should be an easier way to have MoveIt publish its monitored_planning_scene than using dynamic reconfigure. Ioan showed me how to do this programmaticaly with a hack, but it would be better if this was a roslaunch parameter or a checkbox on the motion_planning_plugin. I'd be happy to add this enhancement myself if it is a good idea: I propose a new launch parameter called something like "publish_monitored_planning_scene", the launch file would thus be:

```
  <node name="move_group" launch-prefix="$(arg launch_prefix)" pkg="moveit_ros_planning" type="move_group_action_server" respawn="false" output="screen" args="$(arg command_args)">
    <param name="allow_trajectory_execution" value="$(arg allow_trajectory_execution)"/>
    <param name="max_safe_path_cost" value="$(arg max_safe_path_cost)"/>
>>  <param name="publish_monitored_planning_scene" value="$(arg publish_monitored_planning_scene)"/>
  </node>
```

My overall intent is to be able to quickly path plan using a start state that is the physical robot's current location.

**Comment by isucan** [comment]
The dynamic_reconfigure options are in fact ros params and you can initialize them to desired values in the launch file already.

**Comment by davetcoleman** [comment]
I figured out what parameters and have added this to the moveit_config template files generated in the Setup Assistant in this [commit](https://github.com/ros-planning/moveit-setup-assistant/commit/cd10e48d1faa4b1ea59cb1dd21ba2aa6fbd3f1ea). By default there is no change but if you set the publish_monitored_planning_scene arg to true then it is easy to connect a physical robot to the motion_planning_plugin. 

I personally would prefer this to default to true, but think I should run that by others first.
