### ISSUE TITLE
goal poses not displayed with the PR2

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#114]
For some reason, goal poses in the warehouse are not displayed correctly when loading the PR2 robot. They are loaded and double-clicking on them computes IK on the robot. It's just the interactive markers are not displayed.

**Comment by marioprats** [comment]
This is an issue with the /odom_combined frame that is not published by default in pr2_moveit_config/demo.launch. Running static_transform_publisher solves the problem. @isucan should we include the static transform broadcast odom_combined -> base_link into the demo launch file?

**Comment by isucan** [comment]
Can you add that to the launch file? I will take a look anyway.

**Comment by isucan** [comment]
mario added a launch file fix, so this should be fine; reassigning to me so i don't forget to check why it worked in the past without the transformer

**Comment by marioprats** [comment]
Well, the end-effector interactive markers work even without the broadcaster (as long as you set odom_combined as the fixed frame). But odom_combined was neved published, so the tf tree was broken

**Comment by isucan** [comment]
makes sense
