### ISSUE TITLE
robot_interaction IM are re-created in a loop

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#124]
motion_planning_display sets the changedQueryStartState callback for robot_interaction. This callback is called each time IM feedback is received. Inside the callback, MotionPlanningDisplay::publishInteractiveMarkers gets called, which destroys and creates again the interactive markers. Therefore, IM are destroyed and created in the feedback loop, right?

This creates a significant overload, I was wondering whether there is a reason for that. I've created a new method drawQueryStartState which doesn't call publishInteractiveMarkers, and used it for the callback, thus avoiding re-creating IM in the loop. This makes IK more responsive. If there is nothing bad with that, I can send a pull request.

**Comment by isucan** [comment]
Well, this is actually on purpose. But I think things can be optimized. The resulting behaviour of the setup in there now is that the marker is always at a position that is obtained through FK. If IK was successful, all looks right. If IK failed, the arm snaps back to the last successful pose. But we can probably optimize, in the sense that we only redraw when IK fails and we need the arm to snap back. Does this make sense?

**Comment by marioprats** [comment]
Yes, that would be an improvement. But what is the reason for forcing the IM to be at the last valid IK pose? Personally I find it more usable if we don't move it back to the last valid pose. Sometimes, if a pose is not valid, you may want to search around it for a valid one, without the marker jumping to another place.

**Comment by aleeper** [comment]
I agree with Mario. For teleop, it is critical that the interactive marker
be allowed to stay in kinematically infeasible poses. If it pops back
automatically the user will get really irritated.

**Comment by aleeper** [comment]
After playing around with things in the most recent implementation, I would point out that enforcing that the IK be feasible is restrictive for traditional teleop. For example, someone who wants to send the interactive marker pose to a J-Transpose controller doesn't care whether the pose is kinematically feasible, he just wants the gripper to move in that direction as much as possible. Similarly, my constrained optimization stuff doesn't care if the goal is feasible, it just finds feasible motions that take it closer to the goal.

On a side note, playing with this stuff again after a several-week hiatus, it is so quick and responsive! Nice job :)

**Comment by marioprats** [comment]
This should be already fixed. Now the IM can be moved even outside the reachable space of the arm. Pressing Crtl-R will reset and bring them to the end-effector
