### ISSUE TITLE
Linker errors in occupancy_map_server when building from source

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_ros#125]
Hi,

I'm on a 12.04/groovy machine. After an issue with .deb based install has been corrected (see http://answers.ros.org/question/51308/moveit-groovy-symbol-lookup-error-kdl-plugin/ , thanks for the quick fix! )  I wanted to test a from source install as I didn't want to wait for the new debian packages.

I followed the instructions here:
http://moveit.ros.org/wiki/index.php/Groovy/Source_Install

I then get the following linker errors in occupancy_map_server:

<pre>
Scanning dependencies of target moveit_occupancy_map_monitor
[ 62%] Building CXX object moveit_ros/perception/occupancy_map_monitor/CMakeFiles/moveit_occupancy_map_monitor.dir/src/occupancy_map_monitor.cpp.o
Linking CXX executable /opt/repos/moveit/devel/lib/moveit_ros_perception/test_filter
[ 62%] Building CXX object moveit_ros/perception/occupancy_map_monitor/CMakeFiles/moveit_occupancy_map_monitor.dir/src/point_cloud_occupancy_map_updater.cpp.o
[ 62%] Built target test_filter
[ 63%] Building CXX object moveit_ros/perception/occupancy_map_monitor/CMakeFiles/moveit_occupancy_map_monitor.dir/src/octomap_markers.cpp.o
In file included from /opt/ros/groovy/include/pcl-1.6/pcl/point_types.h:301:0,
                 from /opt/repos/moveit/src/moveit_ros/perception/robot_self_filter/include/moveit/robot_self_filter/self_mask.h:41,
                 from /opt/repos/moveit/src/moveit_ros/perception/occupancy_map_monitor/include/moveit/occupancy_map_monitor/point_cloud_occupancy_map_updater.h:45,
                 from /opt/repos/moveit/src/moveit_ros/perception/occupancy_map_monitor/src/occupancy_map_monitor.cpp:41:
/opt/ros/groovy/include/pcl-1.6/pcl/impl/point_types.hpp:1009:68: warning: ‘SHOT’ is deprecated [-Wdeprecated-declarations]
In file included from /opt/ros/groovy/include/pcl-1.6/pcl/point_types.h:301:0,
                 from /opt/repos/moveit/src/moveit_ros/perception/robot_self_filter/include/moveit/robot_self_filter/self_mask.h:41,
                 from /opt/repos/moveit/src/moveit_ros/perception/occupancy_map_monitor/include/moveit/occupancy_map_monitor/point_cloud_occupancy_map_updater.h:45,
                 from /opt/repos/moveit/src/moveit_ros/perception/occupancy_map_monitor/src/point_cloud_occupancy_map_updater.cpp:37:
/opt/ros/groovy/include/pcl-1.6/pcl/impl/point_types.hpp:1009:68: warning: ‘SHOT’ is deprecated [-Wdeprecated-declarations]
[ 64%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/model_based_planning_context.cpp.o
[ 64%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/parameterization/model_based_joint_state_space.cpp.o
[ 64%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/parameterization/model_based_state_space.cpp.o
[ 64%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/parameterization/model_based_state_space_factory.cpp.o
Linking CXX shared library /opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so
[ 64%] Built target moveit_occupancy_map_monitor
Scanning dependencies of target moveit_occupancy_map_server
[ 64%] Building CXX object moveit_ros/perception/occupancy_map_monitor/CMakeFiles/moveit_occupancy_map_server.dir/src/occupancy_map_server.cpp.o
[ 65%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/parameterization/joint_space/joint_model_state_space.cpp.o
[ 65%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/parameterization/joint_space/joint_model_state_space_factory.cpp.o
Linking CXX executable /opt/repos/moveit/devel/lib/moveit_ros_perception/moveit_occupancy_map_server
[ 65%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/parameterization/work_space/pose_model_state_space.cpp.o
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::AbstractOccupancyOcTree::AbstractOccupancyOcTree()'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::Pointcloud::~Pointcloud()'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::OcTreeNode::addValue(float const&)'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::OcTreeNode::OcTreeNode()'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::OcTreeNode::~OcTreeNode()'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::Pointcloud::transform(octomath::Pose6D)'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomath::Pose6D::~Pose6D()'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomath::Pose6D::inv() const'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomath::operator<<(std::basic_ostream<char, std::char_traits<char> >&, octomath::Vector3 const&)'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::AbstractOccupancyOcTree::writeBinaryConst(std::basic_ostream<char, std::char_traits<char> >&) const'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomath::Pose6D::transform(octomath::Vector3 const&) const'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::Pointcloud::Pointcloud(octomap::Pointcloud const&)'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomath::Quaternion::Quaternion(octomath::Quaternion const&)'
/opt/repos/moveit/devel/lib/libmoveit_occupancy_map_monitor.so: undefined reference to `octomap::OcTreeNode::getMaxChildLogOdds() const'
collect2: ld returned 1 exit status
make[2]: *** [/opt/repos/moveit/devel/lib/moveit_ros_perception/moveit_occupancy_map_server] Error 1
make[1]: *** [moveit_ros/perception/occupancy_map_monitor/CMakeFiles/moveit_occupancy_map_server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/parameterization/work_space/pose_model_state_space_factory.cpp.o
[ 66%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/threadsafe_state_storage.cpp.o
[ 66%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/state_validity_checker.cpp.o
[ 66%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/projection_evaluators.cpp.o
[ 66%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/goal_union.cpp.o
[ 66%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/constrained_sampler.cpp.o
[ 67%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/constrained_valid_state_sampler.cpp.o
[ 67%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/constrained_goal_sampler.cpp.o
[ 67%] Building CXX object moveit_planners/ompl/core/ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/ompl_console.cpp.o
Linking CXX shared library /opt/repos/moveit/devel/lib/libmoveit_ompl_interface.so
[ 67%] Built target moveit_ompl_interface
make: *** [all] Error 2
Invoking "make" failed
</pre>

Any fixes or suggestions on what I'm doing wrong are much appreciated.

**Comment by isucan** [comment]
Ah... This is a separate issue I think. Octomap was just re-released and the source code was updated to build with the new octomap, which you probably do not have a deb for. Try downloading this deb for octomap: 
http://50.28.27.175/repos/building/pool/main/r/ros-groovy-octomap/
Install it, and then try again building from source.

**Comment by skohlbr** [comment]
Thanks again for quickly finding a fix!
Now, compilation fails at a later point when following the wiki's install instructions, created ticket #131 for that issue.
