### ISSUE TITLE
Wiki install instructions fail due to outdated manipulation_msgs being used

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_ros#131]
Following http://moveit.ros.org/wiki/index.php/Groovy/Source_Install and installing an updated Octomap version as suggested in #125, compilation fails later due to some fields not being present in the used manipulation_msgs version:

<pre>
Linking CXX executable /opt/repos/moveit/devel/lib/moveit_ros_warehouse/moveit_save_to_warehouse
[ 76%] Built target moveit_save_to_warehouse
[ 77%] Building CXX object moveit_ros/benchmarks/benchmarks/CMakeFiles/moveit_benchmarks_config.dir/src/benchmarks_utils.cpp.o
[ 78%] Building CXX object moveit_ros/manipulation/pick_place/CMakeFiles/moveit_pick_place_planner.dir/src/approach_stage.cpp.o
[ 78%] Building CXX object moveit_ros/manipulation/pick_place/CMakeFiles/moveit_pick_place_planner.dir/src/plan_stage.cpp.o
[ 78%] Building CXX object moveit_ros/manipulation/pick_place/CMakeFiles/moveit_pick_place_planner.dir/src/output_stage.cpp.o
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp: In member function ‘bool pick_place::ApproachStage::tryDistance(const ManipulationPlanPtr&, double) const’:
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp:72:109: error: ‘manipulation_msgs::Grasp’ has no member named ‘approach_direction’
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp:73:109: error: ‘manipulation_msgs::Grasp’ has no member named ‘approach_direction’
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp:74:109: error: ‘manipulation_msgs::Grasp’ has no member named ‘approach_direction’
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp: In member function ‘bool pick_place::ApproachStage::tryApproach(const ManipulationPlanPtr&, double) const’:
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp:126:80: error: ‘manipulation_msgs::Grasp’ has no member named ‘approach_direction’
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp:127:80: error: ‘manipulation_msgs::Grasp’ has no member named ‘approach_direction’
/opt/repos/moveit/src/moveit_ros/manipulation/pick_place/src/approach_stage.cpp:128:80: error: ‘manipulation_msgs::Grasp’ has no member named ‘approach_direction’
make[2]: *** [moveit_ros/manipulation/pick_place/CMakeFiles/moveit_pick_place_planner.dir/src/approach_stage.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Linking CXX shared library /opt/repos/moveit/devel/lib/libmoveit_benchmarks_config.so
[ 78%] Built target moveit_benchmarks_config
Scanning dependencies of target moveit_call_benchmark
Scanning dependencies of target moveit_run_benchmark
[ 78%] Building CXX object moveit_ros/benchmarks/benchmarks/CMakeFiles/moveit_call_benchmark.dir/src/call_benchmark.cpp.o
[ 78%] Building CXX object moveit_ros/benchmarks/benchmarks/CMakeFiles/moveit_run_benchmark.dir/src/run_benchmark.cpp.o
make[1]: *** [moveit_ros/manipulation/pick_place/CMakeFiles/moveit_pick_place_planner.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
</pre>

I'm quite the catkin noob at this point and have to read up on how to properly do an overlay to prevent this. But at some point (hopefully in the near future :) ) the install instructions on the wiki should work for everyone anyways.

**Comment by isucan** [comment]
The issue is that manipulation_msgs is taken from deb rather than from source. I will fix this

**Comment by isucan** [comment]
if you get the new rosinstall file, that should pull the additional repo. Please re-open if that does not work.

**Comment by skohlbr** [comment]
Yes works, thanks for the very quick fix.
