### ISSUE TITLE
too much computation in main loop of rviz plugin

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#134]
These lines

```
  frame_->updateSceneMarkers(wall_dt, ros_dt);
  frame_->updateGoalPoseMarkers(wall_dt, ros_dt);
```

in the update() call in motion_planning_display.cpp perform too much computation for the frequency at which update() is called. This causes the GUI to hang. For some scenes where there are lots of goal pose markers things no longer work (eg, poping dialogs to import / export CAD files or scene descriptions)
Can we have this update called only when it is needed?
And as much as possible, call it in background? (but not continuously)

**Comment by marioprats** [comment]
Actually it seems the call to updateGoalPoseMarkers is only needed when dragging a multiple selection of goals, so we can probably place it in the dragging feedback. I'll take a look

**Comment by marioprats** [comment]
Should be fixed b365a1abced1656f0a87f2e396936328202be77a

**Comment by adamantivm** [comment]
I am trying to export the same problematic scene as before and unfortunately it keeps getting stuck after this update. Re-opening for the time being, let me know if I should address this somewhere else.

**Comment by adamantivm** [comment]
Concretely the problem I'm experiencing is that, after loading a planning scene and hitting on the "Export As Text" button on the "Scene Objects" tab, the dialog window that opens appears completely blank. This happens consistently for some particular planning scenes which have multiple collision objects and goal poses. See attached screenshot.

![Screenshot from 2013-01-09 12:48:42](https://f.cloud.github.com/assets/400240/57867/28e20036-5b5c-11e2-8647-c72d5277ef89.png)

**Comment by marioprats** [comment]
Not sure on what's happening here. The update() call in motion_planning_display.cpp doesn't update the markers now, but the problem still seems related to the number of goals in the scene... It's weird that other dialogs work fine (add a new goal, remove, etc.), it only happens with the file load dialog. Even without goals, that dialog looks slower than usual to me, so I'm not sure if goals are the only cause...

As a temporary solution, I have submitted a pull request for displaying goals only inside the queries tab. So when you leave the queries tab, the goals are destroyed. And created again when entering the tab. This should allow using the file loading dialogs, and it's probably more convenient terms of the UI

**Comment by marioprats** [comment]
This should be ok after the split
