### ISSUE TITLE
motion_planning_plugin doesn't work nicely with simulated or real robots

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_ros#136]
After following the documentation here: http://moveit.ros.org/wiki/index.php/Groovy/PR2/Gazebo/Quick_Start

...I have found that Rviz never seems to be in sync with Gazebo. 
Has something changed in the plugin, or is it a config/launch issue, or is the documentation broken?

**Comment by isucan** [comment]
This may be missing in the tutorial, but did you enable scene publishing in move_group? You can do that with dynamic_reconfigure. (By default nothing is published)

**Comment by aleeper** [comment]
Ok changing the publishing parameter did the trick, though I had to do it manually since dynamic reconfigure doesn't seem to display the various parameter toggles correctly.

**Comment by aleeper** [comment]
By the way, putting this parameter in the launching of move_group is one way to fix the problem:

<param name="planning_scene_monitor/publish_planning_scene" value="true"/>
