### ISSUE TITLE
add rviz plugin for benchmakring

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#144]
and move some of the stuff from the planning rviz plugin to the new one.

in particular:
definition of goal poses & start states, visualizing benchmark log data

**Comment by marioprats** [comment]
_Update:_ There is a new tool under moveit_ros/benchmarks that already allows defining goals, states and visualizing benchmark results

<tt>rosrun moveit_ros_benchmarks benchmark_tool</tt>

Will close this ticket once we have removed the corresponding tabs in the moveit rviz plugin

**Comment by isucan** [comment]
agreed
