### ISSUE TITLE
offset when loading a planning scene for another robot

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#146]
Using the plugin I'm storing into the warehouse a planning scene created for one robot. When loading it with another radically different robot, it seems to be an offset in the collisions objects position. Interestingly, if instead of loading the scene from the warehouse, I export and import the geometry as text, it seems fine.

Digging into the code I've found the origin of the problem. Inside planning_scene::PlanningScene::processCollisionObjectMsg a transform is applied to all the loaded collisions objects. That transform uses the frame_id field of the object, which may lead to issues when loading scenes across robots. I'm not sure that transform is really needed, since the SceneNode that holds all the collisions shapes is already transformed each time the fixed frame is changed. Actually, removing the transform solves my problem, is this a bug or would that break something else?

**Comment by isucan** [comment]
That transform is needed to take into account the reference frame of the poses specified for the shapes in the collision object, so we cannot remove it. Can you print the value of object.header.frame_id in that function for the different robots? Also print the transform t.translation(); Also, what is the fixed frame for rviz?

**Comment by marioprats** [comment]
I'm printing the frame_id value when loading the scene for robot B, and it is "base_link", which was the model frame when I stored the scene for robot A. This frame may not exist for robot B, or may exist in a very different position. In my case it exists, but has an offset of z=0.05m wrt the model frame of B, which explains the offset in the objects pose. Shouldn't we place the collisions objects relative to each robot model frame, instead of the one they were stored with?

**Comment by isucan** [comment]
Ok, so this means the code id doing exactly what it should :) Do you define a virtual joint defined for these robots? If you define that, and it has the same name for all robots, the transform for that should be identity for all robots so the offset will go away.

**Comment by marioprats** [comment]
Closing, will be addressed in ros-planning/moveit_core#17
