### ISSUE TITLE
Include end_effector geometry in robot_interaction interactive_marker

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_ros#147]
e.g. draw the pr2's gripper in the interactive marker published by robot interaction.

Note: how do we keep the gripper opening value in-sync with the robot? Maybe that has to be done manually by the person using it.

**Comment by isucan** [comment]
is this done?

**Comment by aleeper** [comment]
The mesh geometry is there. The marker won't "track" the state of the underlying links, e.g. if the gripper closes, unless you tell robot interaction to update the markers, at which point the new transforms are used. 

I suppose we should close this for now, though, as that is a bit application specific, and shouldn't happen automatically in any case.
