### ISSUE TITLE
Rviz MotionPlanning arms get stuck while interacting

### ISSUE THREAD

**Issue by acornacorn** [moveit/moveit_ros#148]
When using the MotionPlanning plugin with pr2, with interact clicked, moving the manipulator moves the arm start and end states around.  After dragging for a while the arm gets locked in one position. The manipulator handle still moves but the arm no longer follows it.

**Comment by marioprats** [comment]
Could this be related to #149? if the interactive marker is outside the reachable space, the arm will stay in the last valid state. Bringing the interactive marker back into the workspace (or pressing ctrl-r), should make the arm jump to it.

**Comment by acornacorn** [comment]
Looks like this is a dup of #159 . closing
