### ISSUE TITLE
Rviz MotionPlanning manipulators do not snap back

### ISSUE THREAD

**Issue by acornacorn** [moveit/moveit_ros#149]
when using "interact" to move arms, manipulators are supposed to "snap back" to an acheivable pose when dragged far from the arm.  Currently they do not do this.  It seems like it does work when running both rviz and gazebo, but not when running only rviz.

**Comment by marioprats** [comment]
We recently modified the way interactive markers behave, to allow the user move them beyond the arm workspace, even if the arm can't reach there. When running with gazebo, the planning scene is updated at some rate, and I think this resets the markers to the end-effector pose (should we change that too? or probably a checkbox to select the desired behavior?). Anyway, pressing CRTL-R should bring the interactive markers back to the end-effector.

**Comment by isucan** [comment]
this is caused by the same problem as #159
