### ISSUE TITLE
Visualization of "path"

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_ros#151]
One of the four visualized robots correspond to the "Planned Path", which is meaningful while it is moving but after the planned path is completed it just sits there at the end pose of the previously planned path, so it would be nice to just make it disappear when the motion is done.

**Comment by aleeper** [comment]
This is related to a question I have:
Publishing an empty planning scene to a PlanningSceneDisplay does not "clear" the robot... is there a way to do this?

**Comment by isucan** [comment]
@aleeper what do you mean by clear the robot?

**Comment by isucan** [comment]
we will handle adam's comment as part of #142

**Comment by acornacorn** [comment]
Closing.  Fixed with pull request 167
