### ISSUE TITLE
rosdep needs to be called before roslaunch

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#154]
@dirk-thomas 
When roslaunching stuff, weird errors happen if rosdep had not been called. This seems to be a ROS issue. Do we really need this step?

```
[rospack] Error: the rosdep view is empty: call 'sudo rosdep init' and
'rosdep update'
[librospack]: error while executing command
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  rospack could not find the rviz package containing rviz::Tool
[moveit_setup_assistant-2] process has died [pid 21842, exit code -6,
cmd /wg/stor6_home3/cousins/moveit/devel/lib/moveit_setup_assistant/moveit_setup_assistant
__name:=moveit_setup_assistant
__log:=/u/cousins/.ros/log/478cc88e-60ef-11e2-bbca-00259015ddf6/moveit_setup_assistant-2.log].
log file: /u/cousins/.ros/log/478cc88e-60ef-11e2-bbca-00259015ddf6/moveit_setup_assistant-2*.log
```

**Comment by dirk-thomas** [comment]
From what I get from the (too short) snippet: the rosdep database is not initialized yet and you try to roslaunch something. Then the error message makes perfect sense and you should perform the mentioned commands and then retry. Roslaunch (as well as all other tools) will not invoke rosdep init/update for you.

If I am missing something please provide context about your setup and what commands you run.

**Comment by isucan** [comment]
The problem is that which you metion. What I am saying is that this is a new requirement for ROS and quite confusing. I do not recall having to run rosdep before roslaunch. The names of the tools suggest to me they should not depend on each other, but if there is a good reason to have this dependency, when rosdep is installed, that initialization step should be done as a post-install step.

**Comment by dirk-thomas** [comment]
The step to init/update rosdep is mentioned in the ROS install instructions explicitly.

The enhancement to perform database init on installation has been ticketed for rosdep ros/rosdep#31 but nobody has yet solved that. Patches are welcome :-)

**Comment by isucan** [comment]
this is really an issue how how rospack detects dependency types. closing since not related to moveit
