### ISSUE TITLE
arm freezes in rviz after interacting

### ISSUE THREAD

**Issue by acornacorn** [moveit/moveit_ros#159]
After interacting with the green "Start State" arm for a while, the arm freezes and can no longer be moved.  The manipulator can still be moved around but the arm does not follow.  CTRL-R does nothing.

Repro:
1) Start rviz using the command
roslaunch pr2_moveit_config demo.launch

2) Set up as described in Step1 here:
http://moveit.ros.org/wiki/index.php/Groovy/PR2/Rviz_Plugin/Quick_Start

3) Turn off MotionPlanning::SceneRobot::ShowSceneRobot
Turn off MotionPlanning::PlanningRequest::QueryGoalState
Turn on MotionPlanning::PlanningRequest::QueryStartState

4) click interact.  

5) Drag the manipulator around.  Drag it around again.  After a few times the robot arm stops following the manipulator and does not move anymore.  Pressing CTRL-R has no effect.

If MotionPlanning::PlanningRequest::QueryGoalState is turned on at this point then the orange arm is also frozen.  Sometimes turning this on crashes the program.

**Comment by acornacorn** [comment]
Looks like this is related to recent changes.  Reverting moveit_ros to 51ccf2f43c3c70778be324c19ee2bfe23d52c555 fixes the problem.

**Comment by marioprats** [comment]
Good to know! I was trying to reproduce without success!

**Comment by isucan** [comment]
i believe this is now fixed
