### ISSUE TITLE
execute paths from current robot state only

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#161]
when execution is included, the start state specified in the MotionPlanRequest should be ignored. the current state should be used. Maybe a warning should be issued if a different state is specified.

**Comment by isucan** [comment]
fixed

**Comment by KaijenHsiao** [comment]
Er.  I would say that the start state shouldn't be ignored--the current state should splice onto the front of the plan, if the two are a tiny bit different.  (And maybe a warning if the two states differ by too much.)
