### ISSUE TITLE
render_shapes holds only one ogre material for all meshes

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#177]
...and this ogre material is initialized with the color of the first drawn mesh. As a result, all the meshes are rendered with the same color, even if their colors are actually different. This just happens for meshes. The rest of shapes primitives are rendered correctly.

I guess we should keep a vector of materials, and assign one to each new mesh. If this makes sense I can send a pull request.

**Comment by isucan** [comment]
That makes sense. Pull request welcome :)
