### ISSUE TITLE
Interactive Markers for Scene Objects

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#18]
it's almost unbearably difficult to properly position separate scene objects using the X Y Z and R P Y fields.  The center of rotation is not always on the object and the rotations cause the object to translate around.

Interactive markers would help tremendously with this problem and allow for faster scene creation.

**Comment by marioprats** [comment]
Hi, I'm trying to add interactive markers for placing the collision objects. Let you know when I have something working

**Comment by isucan** [comment]
Mario, thanks for doing this! Are you doing this in the rviz plugin itself?

**Comment by marioprats** [comment]
Yes, I'm using the IM feedback to call the methods you have for positioning the objects. Please tell me if you have another idea.

**Comment by isucan** [comment]
No, that's good. Are you using the same interactive marker server that's in robot_interaction?

**Comment by marioprats** [comment]
No, I started another one, since feedback processing is significantly different for both

**Comment by isucan** [comment]
Ok, sounds reasonable. Either way would be fine I think. Then I presume you are starting corresponding internal display as well, correct? I am asking because I'd like to keep the plugin standalone, not have to ask users to add additional displays.

**Comment by marioprats** [comment]
Ok, I'm testing with an external display now, but will make it internal

**Comment by marioprats** [comment]
I've made a commit of the current state into my fork in case you want to try, or you need it for creating the scenes:

git@github.com:marioprats/moveit-ros.git

You will need to create another IM display in rviz. I'll be working now in doing in internally

**Comment by isucan** [comment]
Looks good to me. For the interactive markers constructed in planning_frame.cpp, would it be possible to add independent functions that construct them to the robot_interaction package? There is an interactive_markers_helper.h file. (If that makes sense only)

**Comment by marioprats** [comment]
Hi, David has refactored the InteractiveMarker class to allow for easy creation of IM without the need of a display. I have commited that to my rviz fork and will go upstream at some time. Using that, I'm creating IM inside the moveit rviz plugin (without the need of a server) for setting the pose of the collision objects. That's in my fork of moveit-ros. Please have a look if you have a time. Basically, now it is possible to set the object's pose both manually as before, or either using IM. For now the IM is created at the origin of the model and at a fixed scale, so it is assumed that the origin of the model is already at a reasonable place.

**Comment by isucan** [comment]
Excellent! That sounds like a nice setup. Is there a chance for this refactor of David's to make it to Groovy? It would be really nice if it did, so we can use it in the Groovy version of MoveIt.

**Comment by marioprats** [comment]
Good, we have placed a pull request for rviz in groovy

**Comment by isucan** [comment]
This was merged in a few days ago
