### ISSUE TITLE
rviz_plugin uses scene robot for setting current state for motion planning query

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_ros#182]
rviz_plugin currently uses the scene robot for setting the current state for motion planning queries. So, if you move the base and then want to setup a query for the right_arm, the configuration of the base jumps back to where the scene robot is. It should instead use the new start state.

**Comment by isucan** [comment]
fixed in 1517aeb10c4c8d6a078ec9e4bd9e8f299213f173
