### ISSUE TITLE
'Planning Time' field is not used

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#19]
The 'Planning Time' field in the rviz plugin is not used.  Right now it is hard configured inside move_group.cpp to 5.0s.  I'm finding many plans require 10 to 15 seconds, so being able to configure this value will be essential.

**Comment by isucan** [comment]
I think you may be using a version that did not have the control implemented yet (just the GUI element). The latest version has this feature implemented. Can you verify?

**Comment by chadrockey** [comment]
Confirmed fixed in latest.
