### ISSUE TITLE
generalize joint_state_group::computeCartesianPath

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#190]
Can we add a new method (possibly built on top of computeCartesianPath) that basically does the same but with a set of waypoints as input? We would use it for benchmarking cartesian trajectories without jumps in the joint state

**Comment by isucan** [comment]
I think that joint_state_group is not really the place for such a function. We can think about perhaps adding a planner that does this. For now, I suggest maybe doing a for loop at the call site?

**Comment by mateiciocarlie** [comment]
I think this would just be another interface to the same functionality, namely computing a Cartesian Path. Sometimes you want to specify a start point, a direction, a distance, and a max jump (what we have now). For other use cases, you just want to specify the waypoints yourself. The functionality underneath is highly similar. 

It feels OK to me for both interface to live in the same place.

**Comment by marioprats** [comment]
I agree both will be very similar. But we can start implementing it on the client side as Ioan suggests (need to first solve #191, since it needs to be called from benchmarks), and later move it into joint_state_group if it makes sense.

**Comment by sachinchitta** [comment]
We are going to get an implementation of this from ros-industrial. joint_state_group would be the right place for integrating an implementation of this.

**Comment by isucan** [comment]
I don't think joint_state_group is the right place for this. We should talk about it some more, but this is not low level enough to exist in joint_state_group (or the robot_state library actually)

**Comment by isucan** [comment]
done by mario
