### ISSUE TITLE
implement state storage tab in mp rviz plugin

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#194]

**Comment by marioprats** [comment]
Hey, I'm not sure of what functionality are you expecting exactly. Should
the "Load state" button load states from the database? In that case, we
need another button for setting the current state of the robot to the
selected state, right? actually, should be two buttons? (start and goal)

**Comment by isucan** [comment]
Yes, make it as two buttons: load into start and load into goal.

**Comment by isucan** [comment]
mario did this
