### ISSUE TITLE
rviz dies when disabling plugin / re-enabling

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#196]
I've experienced multiple times issues with Rviz crashing whenever I disable the Motion Planning plugin, then re-enable it, when I road a config.rviz file that has the Motion Planning Plugin disabled, and sometimes just when I launch Rviz with the Motion Planning plugin enabled in the config file. I'm on shadow-fixed and MoveIt is installed from source with the latest, not sure what the issue is. 

Strangely, when I roslaunch rviz with the debug parameter I can't get it to crash, will update if I do get a backtrack.

The message I get in the terminal is: 

```
[rviz_ros_monster_11276_7484787557672128976-1] process has died [pid 11294, exit code -11, cmd /opt/ros/groovy/lib/rviz/rviz -d /home/dave/ros/clam/src/clam_moveit_config/launch/moveit.rviz __name:=rviz_ros_monster_11276_7484787557672128976 __log:=/home/dave/.ros/log/c1776c10-7177-11e2-b575-d43d7e05aeaf/rviz_ros_monster_11276_7484787557672128976-1.log]
```

Thanks!

**Comment by isucan** [comment]
I think I know what this is -- incorrect locking around query states. I believe it has been fixed in source and latest debs.

**Comment by davetcoleman** [comment]
This issue is still occurring with the latest source

**Comment by isucan** [comment]
is this still happening?

**Comment by davetcoleman** [comment]
will check soon.

**Comment by davetcoleman** [comment]
unable to check because of https://github.com/ros-planning/moveit_planners/issues/9

**Comment by davetcoleman** [comment]
I haven't seen it really, I'll just go ahead and close this ticket for now.
