### ISSUE TITLE
Weird EE interactive marker visual in Plugin

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#197]
The interactive marker of both the Start and Goal States of the Planning Request has odd visual as shown in picture below. It goes away when I leave Interact mode (ie switch to Move Camera mode). It appears to have a large square of infinite size starting at the origin of the gripper finger. Its probably related to the way I semantically defined my EE in the SRDF, but I'm not sure what to do and this behavior is certainly a bug.

![Screenshot from 2013-02-07 16:00:58](https://f.cloud.github.com/assets/561060/137813/3c7ac7a0-717c-11e2-9474-3d54d700fbf8.png)

![Screenshot from 2013-02-07 16:17:59](https://f.cloud.github.com/assets/561060/137818/a3c8c95c-717c-11e2-8a81-00f1711a005e.png)

Thanks!

**Comment by isucan** [comment]
can you send me an archive of the config folder so i can run this locally?

**Comment by davetcoleman** [comment]
To recreate the issue:
Setup this workspace for the ClamArm
https://github.com/davetcoleman/clam_catkin

Run these two commands:
roslaunch clam_bringup clam_simulation.launch
roslaunch clam_moveit_config_sim move_group.launch

Add the Motion Planning Plugin to Rviz and you should see the out-of-scale mesh when you are in Interact mode.
(Upon further investigation I see it is just the gripper mesh scaled a very large amount)

**Comment by davetcoleman** [comment]
I have submitted a pull request fix for this issue:
https://github.com/ros-planning/moveit_core/pull/45
