### ISSUE TITLE
How To Use Benchmark Tools

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#206]
I have MoveIt installed from source and it controls my robot correctly. I'd like to be able to benchmark various planner's performance. I tried following the instructions [here](http://moveit.ros.org/doxygen/moveit_benchmarking.html#visualizing_benchmark_results).

I have a launch file for starting the server:

```
<launch>
  <node name="moveit_benchmark_server" pkg="moveit_ros_benchmarks" type="moveit_run_benchmark" respawn="false" output="screen">
    <rosparam command="load" file="$(find clam_moveit_config)/config/kinematics.yaml"/>
    <rosparam command="load" file="$(find clam_moveit_config)/config/ompl_planning.yaml"/>
  </node>
</launch>
```

Which I launch.

I have a config file:

```
[scene]
name=test_scene_1
output=mylocation.log
runs=2

[plugin]
name=ompl_interface_ros/OMPLPlanner
planners=KPIECEkConfigDefault RRTConnectkConfigDefault
runs=10
```

I have a planning request using the interactive markers in Rviz within the Motion Planning Plugin:
![Screenshot from 2013-02-22 12:05:34](https://f.cloud.github.com/assets/561060/186170/e0600144-7d22-11e2-9ea9-7db9254758a8.png)

I then run the command 
`rosrun moveit_ros_benchmarks moveit_call_benchmark --planners-only config1.cfg`

And I get the feedback/error:

```
 INFO ros.moveit_ros_benchmarks: Loading '--planners-only'...
ERROR ros.moveit_ros_benchmarks: Unable to open file '--planners-only'
 INFO ros.moveit_ros_benchmarks: Loading 'config1.cfg'...
 INFO ros.moveit_ros_benchmarks: Calling benchmark with options:
Benchmark for scene 'test_scene_1' to be saved at location 'mylocation.log'
Planning requests associated to the scene that match '.*' will be evaluated
Plugins:
   * name: ompl_interface_ros/OMPLPlanner (to be run 10 times for each planner)
   * planners: KPIECEkConfigDefault RRTConnectkConfigDefault

 INFO ros.moveit_ros_benchmarks: No specified start state. Running benchmark once with the default start state.
 INFO ros.moveit_ros_benchmarks: Benckmarking query 'Motion Plan Request 0' (1 of 1)
 INFO ros.moveit_ros_benchmarks: Calling planner benchmark...
ERROR ros.roscpp: Service call failed: service [/benchmark_planning_problem] responded with an error: No projection evaluator specified
ERROR ros.moveit_ros_benchmarks: Failed
 INFO ros.moveit_ros_benchmarks: Processed 1 benchmark configuration files
```

Additionally the benchmarking server gives me this feedback/error:

```
 INFO ros.moveit_ros_benchmarks: Benchmarking planning interfaces:
 INFO ros.moveit_ros_benchmarks: 
  * OMPL executed 10 times
    - KPIECEkConfigDefault
    - RRTConnectkConfigDefault

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
** INFO ros.rosconsole_bridge.console_bridge: Planner configuration 'arm[KPIECEkConfigDefault]' will use planner 'geometric::KPIECE'. Additional configuration parameters will be set when the planner is constructed.
 INFO ros.ompl: Attempting to use default projection.
ERROR ros.ompl: No default projection is set. Perhaps setup() needs to be called
ERROR ros.roscpp: Exception thrown while processing service call: No projection evaluator specified
```

What am I doing wrong? I'd like to add to the wiki these instructions, but I first need to understand myself how to use the benchmarking tools. Thanks!

**Comment by davetcoleman** [comment]
Ioan has helped me through this issue, thanks!

The key was in ompl_planning.yaml in my MoveIt config package... add to the planning group:

```
  projection_evaluator: joints(shoulder_pan_joint,shoulder_pitch_joint)
  longest_valid_segment_fraction: 0.05
```

**Comment by amdshameer** [comment]
@davetcoleman I did everything as it is mentioned http://moveit.ros.org/wiki/Benchmarking I get the following message. But it is not generating log file in the place it is supposed to do. Could you please help me with this? 

My config file has:
[scene]
name=industrial
output=/home/shameer/bench.log
runs=2

[plugin]
name=ompl_interface/OMPLPlanner
planners=KPIECEkConfigDefault RRTConnectkConfigDefault
runs=10

I have ROS Hydro and Ubuntu 12.04

![error_message](https://cloud.githubusercontent.com/assets/3973522/8129162/887faf9a-1106-11e5-973f-0ea65d067398.png)

**Comment by davetcoleman** [comment]
i do not recall how to use benchmarking, sorry
