### ISSUE TITLE
addMesh method into PlanningSceneInterface??

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#209]
Would it make sense to create an 'addMesh' method to PlanningSceneInterface, similar to addSphere, addCone, etc. There is an implementation of it right now in the rviz plugin, I was wondering whether that should be moved here...

**Comment by isucan** [comment]
Yes, we should add that. However that API will have to be reworked. Do you use that code? In C++ or Python?

**Comment by marioprats** [comment]
In C++ I need to add a mesh to a planning scene. I took the implementation
from the rviz plugin and then I saw this API

**Comment by isucan** [comment]
You should not use this API for that.
You should either use getCollisionWorldNonConst()  on a scene, and
addToObject() there;
Or, if you have a moveit_msgs::CollisionObject, call processCollisionObject
on a PlanningScene instance.
Let me know if I can help. Thanks for pointing this out!

Ioan

**Comment by marioprats** [comment]
That's what the rviz plugin is doing, and what I'm doing as well, with a
previous call to createMeshFromResource. But then I discovered the
PlanningSceneInterface API with other similar methods and was wondering
whether it should go there. But if not I will keep using addToObject.
Thanks!
