### ISSUE TITLE
Rviz Motion Planning plugin grinds to a halt when set to monitored_planning_scene

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#211]
I can't seem to track down the cause, but when I upgraded from 0.3.21 to 0.3.24, I am no longer able to set "Planning Scene Topic" to "move_group/monitored_planning scene" without rviz grinding to a major halt.

**Comment by isucan** [comment]
Can you tell me what you are running to get this to happen?

**Comment by mikeferguson** [comment]
@isucan could this same code be in the "show trail" part of the plugin? I notice that showing a trail also really, really slows things down (it used to not be the fastest thing, but now seems much slower).

**Comment by isucan** [comment]
I think this is the same issue. A fix was pushed to rviz, but I am not sure if relased. With the new rviz, things should be back to normal.
