### ISSUE TITLE
Planning scene meshes rendering issues (when added to demo.launch scenario)

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_ros#212]
When launching the 'demo.launch' created by the setup assistant and adding a mesh, I get some issues with mesh rendering:
1. When first importing the mesh, backface culling seems to be inverted, drawing the backfacing polys instead of the front facing ones. One the mesh is attached to a frame of the planning scene, this effect disappears.
2. When playing back a planned trajectory, the mesh flickers and is randomly rendered in either the start, goal or joint violation colors.

This is on a Precise/ROS Groovy/AMD64 setup with MoveIt! installed and compiled from source (fresh checkout from this morning).

**Comment by isucan** [comment]
Can you try to set the scene alpha to 1.0 and see if that changes anything? i suspect that might be the issue for number (1)
For (2), I suspect you have multiple robots drawn in different colors, on top of each other. Can you try disabling some to see if anything changes?

**Comment by skohlbr** [comment]
Sorry for the slight delay. Updates:
1. Yes, setting alpha to 1 solves the visualization issue.
2. I just discovered that the scene object is drawn once for the start, goal and scene state. If the robot remains stationary, all of those will be on top of each other, leading to the flickering effect I observed.

**Comment by isucan** [comment]
Thanks! Should I then mark this as closed?

**Comment by skohlbr** [comment]
Yes, can be marked closed.
1) is a minor inconvenience, might make sense to set alpha to 1 by default to prevent things from looking weird at the beginning
2) also more of an inconvenience. This happens everytime a collision object has the same pose in the start and goal config though, so there might be more people wondering about this in the future.
