### ISSUE TITLE
Kinematics Reachability Fails if fixed frame is not parent of arm group

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#22]
I added the arm to a robot base using a fixed frame.

The tree looks like this (all fixed frames):
/base_link ->torso_link->arm_base_link

I set the kinematics reachability to use /base_link as the '~frame_id", but it complained about:
/moveit/planning_models/src/transforms.cpp:123(Transforms::getTransform ...
 Unable to transform from frame 'torso_link' to frame 'base_link'

This transform was a fixed joint specifying a z offset of around 20cm.  When run, it would compute reachability with an offset of 20cm, as if it did not take this link into account.

The fix was to add the fixed joint into the srdf's 'arm' group, along with the rest of the arm.  This means that the arm group has to have an immediate parent of the frame_id or the reachability tool does not produce the right output.

**Comment by sachinchitta** [comment]
This tool has been deprecated but this functionality will find support in the workspace analysis gui in the future.
