### ISSUE TITLE
Merge Benchmark Server and Client

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#222]
After discussing with Ioan it seems there is no need to have a service request between the server and client. I believe @isucan agreed to make this merge.

**Comment by isucan** [comment]
will do

**Comment by marioprats** [comment]
Does that mean there will be a C++ API for benchmarking?

**Comment by isucan** [comment]
Yes. Do you foresee a problem with such a setup?

**Comment by marioprats** [comment]
No, it's actually a +1 !!

**Comment by isucan** [comment]
done

**Comment by isucan** [comment]
turns out this was dup of #192

**Comment by davetcoleman** [comment]
nice!
