### ISSUE TITLE
Move MoveGroupCapability implementations into library

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_ros#223]
To be able to extend/change the current move_group_action_server implementation, it would be useful to have all MoveGroupCapabilities implementations provided in a library that can be used in another package. Alternatively, they could be moved to a separate package that can be depended on.

The patch below splits up the current moveit_ros_move_group package setup to provide a library and a executable using that library. Any other ideas for providing better reusability are welcome too.

<pre>
diff --git a/move_group/CMakeLists.txt b/move_group/CMakeLists.txt
index 2c054f3..9cfe497 100644
--- a/move_group/CMakeLists.txt
+++ b/move_group/CMakeLists.txt
@@ -17,6 +17,7 @@ find_package(catkin REQUIRED COMPONENTS
 
 catkin_package(
   LIBRARIES
+   moveit_move_group
   INCLUDE_DIRS
     include
   CATKIN_DEPENDS
@@ -33,20 +34,29 @@ include_directories(SYSTEM
 link_directories(${Boost_LIBRARY_DIRS})
 link_directories(${catkin_LIBRARY_DIRS})
 
-add_executable(move_group_action_server
+add_library(moveit_move_group
   src/move_group_capability.cpp
   src/move_group_move_action_capability.cpp
   src/move_group_pick_place_action_capability.cpp
   src/move_group_plan_service_capability.cpp
   src/move_group_execute_service_capability.cpp
-  src/move_group_query_planners_service_capability.cpp  
+  src/move_group_query_planners_service_capability.cpp
   src/move_group_kinematics_service_capability.cpp
   src/move_group_state_validation_service_capability.cpp
   src/move_group_cartesian_path_service_capability.cpp
+  )
+
+target_link_libraries(moveit_move_group ${catkin_LIBRARIES} ${Boost_LIBRARIES})
+
+install(TARGETS moveit_move_group LIBRARY DESTINATION lib)
+
+
+add_executable(move_group_action_server
   src/move_group.cpp
   )
 
-target_link_libraries(move_group_action_server ${catkin_LIBRARIES} ${Boost_LIBRARIES})
+target_link_libraries(move_group_action_server moveit_move_group ${catkin_LIBRARIES} ${Boost_LIBRARIES})
+
 
 install(TARGETS move_group_action_server RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
 install(DIRECTORY include/ DESTINATION include)
</pre>

**Comment by isucan** [comment]
how urgent is this feature request? we are now working on making the capabilities plugins, so it will be easy to configure move_group -- load which capabilities you want, and you would also get each capability as a lib. would this address your issue?

**Comment by skohlbr** [comment]
Perfect, that is a even cleaner solution. Everything I'm doing is extremely urgent ;) but knowing the plans I'll use a temporary hack and switch to plugins once available.

**Comment by isucan** [comment]
MoveGroup capabilities are now plugins
