### ISSUE TITLE
planning_scene_monitor dies after attaching an object to a link

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#229]
I have a planning scene monitor that is running a state updater and the occupancy map monitor. I see the octomap and the robot being updated in rviz. Then I attach a collision object to a robot link, and works fine. But after a while (some 20-30 seconds), the planning scene monitor dies. This is the trace:
#0  0x00007ffff5553038 in __fprintf_chk () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff08b94f8 in qh_check_points () from /usr/lib/libqhull.so.5
#2  0x00007ffff089cbc9 in qh_new_qhull () from /usr/lib/libqhull.so.5
#3  0x00007ffff4fdc7e5 in bodies::ConvexMesh::useDimensions(shapes::Shape const*) () from /opt/ros/groovy/lib/libgeometric_shapes.so
#4  0x00007ffff4fdad5a in bodies::Body::setDimensions(shapes::Shape const*) () from /opt/ros/groovy/lib/libgeometric_shapes.so
#5  0x00007ffff4fe27ab in bodies::createBodyFromShape(shapes::Shape const*) () from /opt/ros/groovy/lib/libgeometric_shapes.so
#6  0x00007fffc11a33f4 in point_containment_filter::ShapeMask::addShape(boost::shared_ptr<shapes::Shape const> const&, double, double)

```
() from /home/mprats/ros/groovy/binfrastructure/devel/lib/libmoveit_point_containment_filter.so
```
#7  0x00007fffc13caab8 in occupancy_map_monitor::PointCloudOctomapUpdater::excludeShape(boost::shared_ptr<shapes::Shape const> const&)

```
() from /home/mprats/ros/groovy/binfrastructure/devel/lib/libmoveit_pointcloud_octomap_updater_core.so
```
#8  0x00007ffff207f6f2 in occupancy_map_monitor::OccupancyMapMonitor::excludeShape(boost::shared_ptr<shapes::Shape const> const&) ()

   from /home/mprats/ros/groovy/binfrastructure/devel/lib/libmoveit_occupancy_map_monitor.so
#9  0x00007ffff5fdd133 in planning_scene_monitor::PlanningSceneMonitor::excludeAttachedBodyFromOctree(robot_state::AttachedBody const*) () from /home/mprats/ros/groovy/binfrastructure/devel/lib/libmoveit_planning_scene_monitor.so
#10 0x00007ffff5fdd404 in planning_scene_monitor::PlanningSceneMonitor::excludeAttachedBodiesFromOctree() ()

   from /home/mprats/ros/groovy/binfrastructure/devel/lib/libmoveit_planning_scene_monitor.so
#11 0x00007ffff5fe476f in planning_scene_monitor::PlanningSceneMonitor::scenePublishingThread() ()

   from /home/mprats/ros/groovy/binfrastructure/devel/lib/libmoveit_planning_scene_monitor.so
#12 0x00007ffff3d3cce9 in thread_proxy () from /usr/lib/libboost_thread.so.1.46.1
#13 0x00007ffff78dae9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#14 0x00007ffff553dcbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#15 0x0000000000000000 in ?? ()

I'm using moveit_ros and moveit_core from source, the rest from debs

**Comment by isucan** [comment]
When did you last update? I fixed an issue a few hours ago that could very well be the cause of this. Can you update just in case?

**Comment by marioprats** [comment]
Seems to be a problem with the mesh. Closing, thanks!
