### ISSUE TITLE
Allow overriding URDF encoded joint position limits in joint_limits.yaml

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#23]
Currently, joint_limits.yaml allows overriding the max_velocity and max_acceleration for a joint.

For programmatic reasons, it would be convenient to also be specify joint limits for position that would take precedence over those in the URDF.

These could be named 'upper_position_limit' and 'lower_position_limit'.  These would be ignored for continuous and fixed joints.

An example configuration would be as follows:
joint_limits:
    revolute_joint:
        lower_position_limit: 0.0
        upper_position_limit: 1.0
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
    prismatic_joint:
        lower_position_limit: -0.2
        upper_position_limit: 0.2
        has_velocity_limits: true
        max_velocity: 0.05
        has_acceleration_limits: true
        max_acceleration: 10.0
    continuous_joint:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 2.0

**Comment by isucan** [comment]
I added this functionality as "max_position" and "min_position" to be optionally specified in the joint_limits.yaml.
