### ISSUE TITLE
Cannot start motion planning plugin in rviz: XML is malformed or missing

### ISSUE THREAD

**Issue by wouterbac** [moveit/moveit_ros#231]
Hello,

Last week I succesfully started the pr2 demo when issuing: roslaunch pr2_moveit_config demo.launch

However, today I tried it again and received the following error:
auto-starting new master
process[master]: started with pid [31286]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d0e7c046-abf6-11e2-ad4e-f0def10f53ff
process[rosout-1]: started with pid [31299]
started core service [/rosout]
process[virtual_joint_broadcaster_0-2]: started with pid [31311]
process[joint_state_publisher-3]: started with pid [31323]
process[robot_state_publisher-4]: started with pid [31324]
process[move_group-5]: started with pid [31325]
/opt/ros/groovy/lib/robot_state_publisher/robot_state_publisher
[ WARN] [1366708736.771670481]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
process[rviz_T510_31272_819321166069983287-6]: started with pid [31342]
process[mongo_wrapper_ros_T510_31272_6952938395260209898-7]: started with pid [31343]
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
[ INFO] [1366708742.665830944]: rviz version 1.9.28
[ INFO] [1366708742.665933025]: compiled against OGRE version 1.7.4 (Cthugha)
[ERROR] [1366708752.298270604]: Skipping XML Document "/home/wouter/ros/workspace/moveit/build/moveit_planners/ompl/catkin_generated/stamps/moveit_planners_ompl/ompl_interface_plugin_description.xml" which had no Root Element.  This likely means the XML is malformed or missing.
[ERROR] [1366708752.298435225]: Skipping XML Document "/home/wouter/ros/workspace/moveit/build/moveit_pr2/pr2_moveit_plugins/catkin_generated/stamps/pr2_moveit_plugins/pr2_moveit_sensor_manager_plugin_description.xml" which had no Root Element.  This likely means the XML is malformed or missing.
[ERROR] [1366708752.298527795]: Skipping XML Document "/home/wouter/ros/workspace/moveit/build/moveit_pr2/pr2_moveit_plugins/catkin_generated/stamps/pr2_moveit_plugins/pr2_moveit_controller_manager_plugin_description.xml" which had no Root Element.  This likely means the XML is malformed or missing.

Do you have any idea what caused this error. It seems the error is related to rviz, but I have the most recent debians installed on my pc with Ubuntu 12.04 and ROS groovy.

Thanks,
Wouter

**Comment by wouterbac** [comment]
Allright, solved it! It seems I manually need to source the following files:
source /opt/ros/groovy/setup.bash
source ~/ros/workspace/moveit/devel/setup.bash

Actually I already had these lines in my .bashrc. But, for some reason these files are not sourced correctly...

These are the last lines of my .bashrc:
source /opt/ros/groovy/setup.bash
source /opt/halcon/.profile_halcon
source ~/ros/workspace/moveit/devel/setup.bash
export ROS_PACKAGE_PATH=~/ros/workspace:~/ros/trunk:$ROS_PACKAGE_PATH

Any idea what went wrong here?

**Comment by isucan** [comment]
This line should not be in your environment:
`export ROS_PACKAGE_PATH=~/ros/workspace:~/ros/trunk:$ROS_PACKAGE_PATH`
That adds your build/ folder to the package path and that is what was causing your problems.

Please follow the instructions on
http://moveit.ros.org/wiki/index.php/Groovy/Installation
The bottom part has instructions on how to build from source.
