### ISSUE TITLE
Add support for joint_limits.yaml in kinematics_reachability workspace.launch

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#24]
This tool should also support joint_limits.yaml if it has been uploaded into the 'robot_description_planning' namespace.

**Comment by isucan** [comment]
If this code uses the planning_models_loader library, this bug is then implicitly fixed by the fix to #23

**Comment by isucan** [comment]
Can anyone confirm if this works?

**Comment by sachinchitta** [comment]
This tool has been deprecated and this functionality has been fixed elsewhere. Reopen if still an issue.
