### ISSUE TITLE
touch_links for attached object being manipulated gets duplicated each time it is published

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#241]
I subscribed to move_group/monitored_planning_scene a noticed that the "touch_links" array of my attached object had grown to a huge size. Basically, it appears that every time planning_scene_monitor publishes a new message, the set of actual touch links keeps getting appended to the list of touch links, causing the number of links to be N*M where N is the correct # of touch links and M is the number of messages that have been published since this object was attached.

I cannot find exactly where this error is happening -- it appears that the internal robot_state for move_group is not being affected, only the message published.

This also happens with the pr2 tutorial for pick_and_place. While this doesn't appear to break anything, it does mean that the message grows larger and larger.

**Comment by isucan** [comment]
I think this is now fixed:
https://github.com/ros-planning/moveit_core/commit/8b825d318c0624e862c6c84306153f796cb2c376

**Comment by mikeferguson** [comment]
So I did a full source build last night -- still looks like this is happening (at least on Maxwell, didn't try the PR2 tutorial).

**Comment by mikeferguson** [comment]
Appears to have been fixed at some point -- all good.
