### ISSUE TITLE
No moveit_commander in 

### ISSUE THREAD

**Issue by sotte** [moveit/moveit_ros#243]
Hey,

first of all: great work! I really like moveit!

After the RosCon I wanted to play with the `moveit_commander`. So I followed this [tutorial](http://moveit.ros.org/wiki/index.php/Groovy/MoveIt_Commander). Sadly there is no `moveit_commander`.

I'm running a current version of groovy with basically all moveit packages installed, especially the `ros-groovy-moveit-commander` package. Am I missing something?

```
> roscd moveit_commander
/o/r/g/s/moveit_commander> tree                  
.
├── cmake
│   ├── moveit_commanderConfig.cmake
│   └── moveit_commanderConfig-version.cmake
└── package.xml

1 directory, 3 files
```

**Comment by isucan** [comment]
hey, this is an issue of installation location. i will address his soon, but in the meantime you can run the executable by hand: it is located in /opt/ros/groovy/bin ; 
could you close the issue if you find it?

**Comment by sotte** [comment]
Thanks, it's there.
