### ISSUE TITLE
Benchmarking RRT* failure

### ISSUE THREAD

**Issue by d-om** [moveit/moveit_ros#244]
since MoveIt! - release:

executing a benchmark for RRT\* with "RRTStarkConfigDefault" (all default settings and launch files generated by the SetupAssistant) causes a moveit_benchmark - crash with exit code 11. (All other planner work fine)
Inside the Rviz-Moveit_plugin "RRTStarkConfigDefault" works correctly.

**Comment by isucan** [comment]
This was a bug in OMPL that got fixed since.
