### ISSUE TITLE
Rviz-Movit-Plugin dies due to scene-name conflict

### ISSUE THREAD

**Issue by d-om** [moveit/moveit_ros#245]
When a scene is named like an allreday existing one, Rviz-Movit-Plugin dies after the warning messsage was confirmed.

**Comment by isucan** [comment]
I can't seem to be able to replicate this.
Can you run moveit_rviz.launch separately with the argument debug:=true and send me a backtrace? 
Ideally multiple backtraces if they are not always the same.

**Comment by d-om** [comment]
I send you the entire log-folder.

I hope this is what you wanted.

Von: isucan [mailto:notifications@github.com] 
Gesendet: Samstag, 18. Mai 2013 21:34
An: ros-planning/moveit_ros
Cc: rosrookie
Betreff: Re: [moveit_ros] Rviz-Movit-Plugin dies due to scene-name conflict (#245)

I can't seem to be able to replicate this.
Can you run moveit_rviz.launch separately with the argument debug:=true and send me a backtrace? 
Ideally multiple backtraces if they are not always the same.

**Comment by isucan** [comment]
I don't think the folder made it through. In any case, what I would actually like is a backtrace, not the log folder.
so you run the command 

```
roslaunch pr2_moveit_config moveit_rviz.launch debug:=true
```

Once you make the code crash, you will be dropped to a command line (gdb) where you would time the command 'bt'
That gives you a  backtrace. Please resize the window it if is too long. Then paste that text to this ticket.

**Comment by d-om** [comment]
Sorry, but I’m not dropped to a command line.( I do not use any IDE. )

There is only the Terminal with the red error-message. 

(The debug-param was set )

Von: isucan [mailto:notifications@github.com] 
Gesendet: Montag, 20. Mai 2013 17:06
An: ros-planning/moveit_ros
Cc: rosrookie
Betreff: Re: [moveit_ros] Rviz-Movit-Plugin dies due to scene-name conflict (#245)

I don't think the folder made it through. In any case, what I would actually like is a backtrace, not the log folder.
so you run the command 

roslaunch pr2_moveit_config moveit_rviz.launch debug:=true

Once you make the code crash, you will be dropped to a command line (gdb) where you would time the command 'bt'
That gives you a backtrace. Please resize the window it if is too long. Then paste that text to this ticket.

**Comment by acornacorn** [comment]
Closing.  If you are still experiencing this bug please reopen and provide more details.
