### ISSUE TITLE
Non-deterministic scene loading behavior in RViz plugin

### ISSUE THREAD

**Issue by joschu** [moveit/moveit_ros#246]
I'm trying to publish a planning scene from an external  program, by publishing to the /planning_scene topic.
Half the time I run my program, the planning scene objects show up RViz, and half the time they don't.
I checked with "rostopic listen" that the message on /planning_scene is getting published 100% of the time.

Here's a minimal script

import roslib.message as rm
import moveit_msgs.msg as mm
import yaml

ps=mm.PlanningScene()

with open("/tmp/planning_scene.yaml","r") as fh: d = yaml.load(fh)
rm.fill_message_args(ps, d)

import rospy
rospy.init_node("republish_scene")
pub = rospy.Publisher("/planning_scene", mm.PlanningScene)
rospy.sleep(.25)
pub.publish(ps)
rospy.sleep(.25)

planning_scene.yaml is exactly the message emitted after doing Import From Text on bookshelves.scene, and the text is here: http://pastebin.com/ruU7Rba8

I'm using the latest MoveIt packages on Oneric. 

I started up rviz with "roslaunch pr2_moveit_config demo.launch"

**Comment by isucan** [comment]
This is not very scientific, but can you increase your delays? and maybe add a spin at the end of your code?
Can you also run a rostopic echo in a separate terminal to check whether the data gets published?

**Comment by joschu** [comment]
Good guess :)
Changing to rospy.sleep(.1) makes it always fail
Changing to rospy.sleep(.5) makes it always succeed

I was indeed checking that the data got published with "rostopic echo" (I mistakenly said "rostopic listen" in my original post)

I added spin() at the end of my code, no effect with sleep(.1) or sleep(.5)

**Comment by joschu** [comment]
I take it that this is a ROS bug, not a MoveIt bug? 
Is it a known issue that messages are sometimes lost (non-deterministically), depending on how much time you leave before and after publishing?

**Comment by isucan** [comment]
unfortunately, yes, it is a ros bug

**Comment by adamantivm** [comment]
I would be willing to bet it's a problem with the way topic publishers are implemented in rospy.
What is almost certainly happening is that when you call rospy.Publisher(), ROS needs to follow a multi-step network protocol to connect with subscribers of the topic (in this case MoveIt). If you issue a "publish()" right after you create the Publisher, then chances are that the publisher will try to send the message before the subscriber (MoveIt) is connectec to it, so MoveIt will miss this publication.
I have been myself bitten by this bug when doing similar things with ROS without MoveIt. My conclusion is that it is highly recommended to create your Publishers as early as possible in your code and make sure you wait at least one second before publishing any message. It also helps if you publish the message more than once, which in most cases doesn't cause any bad side-effects. Finally, you can also try making the Publisher a "latched topic", by passing latch=True in the constructor of the Publisher, which is supposed to keep the last message in memory until after each subscriber is connected, but I haven't tried this with rospy myself.
