### ISSUE TITLE
gomp

### ISSUE THREAD

**Issue by andfil** [moveit/moveit_ros#249]
The code was not building for me until I've changed a line in perception/point_containment_filter/CMakeLists.txt from

target_link_libraries(${MOVEIT_LIB_NAME} ${catkin_LIBRARIES} ${Boost_LIBRARIES})

to

target_link_libraries(${MOVEIT_LIB_NAME} ${catkin_LIBRARIES} ${Boost_LIBRARIES} gomp)

Let me know if I did something wrong. If it's correct, I guess it makes sense to fix it in the main source tree as well.

**Comment by isucan** [comment]
Not sure... things seem fine for other machines. Given your other boost linking errors, are you sure everything is ok on your machine?

**Comment by andfil** [comment]
It seems pretty normal, runs a lot of ROS stuff for me, and compiles small ROS packages nicely. I'll be happy to supply any env/config information that would be helpful.

**Comment by isucan** [comment]
I added a missing link flag: https://github.com/ros-planning/moveit_ros/commit/831fd397dba7dbd6fbfcacdb6d8de287620be4b0
