### ISSUE TITLE
libbost

### ISSUE THREAD

**Issue by andfil** [moveit/moveit_ros#250]
Should I install a particular version of boost / python or modify some CMakeLists.txt to make moveit_ros compile from source?
I get a bunch of errors in the lines of [the output is abbreviated, there are many more undefined references in libbost_python.so]:

Linking CXX executable 
devel/lib/pr2_moveit_tutorials/planning_pipeline_tutorial
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libboost_python.so: error: undefined reference to 'PyList_Insert'

Linking CXX executable 
devel/lib/pr2_moveit_tutorials/motion_planning_interface_tutorial
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libboost_python.so: error: undefined reference to 'PyList_Insert'

Built target moveit_planning_scene_interface_python
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libboost_python.so: error: undefined reference to 'PyList_Insert'

**Comment by isucan** [comment]
This is weird. What compiler /linker are you using?

**Comment by andfil** [comment]
If catkin/make use gcc, then mine is 4.6:

$ls -l /usr/bin/gcc
lrwxrwxrwx 1 root root       7 Oct 25  2012 /usr/bin/gcc -> gcc-4.6

$dpkg -l|grep gcc
ii  gcc                                         4:4.6.3-1ubuntu5                                    GNU C compiler
ii  gcc-4.6                                     4.6.3-1ubuntu5                                      GNU C compiler
ii  gcc-4.6-base                                4.6.3-1ubuntu5                                      GCC, the GNU Compiler Collection (base package)
ii  gcc-4.6-base:i386                           4.6.3-1ubuntu5                                      GCC, the GNU Compiler Collection (base package)
ii  gcc-avr                                     1:4.5.3-3                                           The GNU C compiler (cross compiler for avr)
ii  gccxml                                      0.9.0+cvs20111013-1                                 XML output extension to GCC
ii  lib32gcc1                                   1:4.6.3-1ubuntu5                                    GCC support library (32 bit Version)
ii  libgcc1                                     1:4.6.3-1ubuntu5                                    GCC support library
ii  libgcc1:i386                                1:4.6.3-1ubuntu5                                    GCC support library

**Comment by t-thanh** [comment]
Just add -lpython2.7 
--target_link_libraries(<your_excutable_file> ${catkin_LIBRARIES} ${Boost_LIBRARIES})
-+target_link_libraries(<your_excutable_file> ${catkin_LIBRARIES} ${Boost_LIBRARIES} -lpython2.7)
In the CMakeLists.txt

**Comment by isucan** [comment]
Is this still a problem? I have yet ben unable to reproduce this.

**Comment by sachinchitta** [comment]
Please reopen if this is still an issue.
