### ISSUE TITLE
Document use of position-only IK and <6DOF IK

### ISSUE THREAD

**Issue by rguzman1** [moveit/moveit_ros#257]
Hi,

is there a way to use the interactive markers in MoveIt in order to mark only a goal position (not fixing also the euler angles)?

With this 5DOF arm, I am only able to set new target locations moving in XZ, but not in Y as the wrist has only 2DOF and it cannot adapt.

Thanks,

   Roberto

![captura de pantalla de 2013-06-03 17 30 27](https://f.cloud.github.com/assets/4610087/612182/67c22c06-cde7-11e2-8ee6-d3d76f9054de.png)

**Comment by isucan** [comment]
Right now there is not such functionality exposed. However, it should be
easy to add I think. @acornacorn the stuff you added for controlling just
certain dof in robot interaction - is it easy to expose that functionality
with a checkbox of some kind? The more difficult part will be generating
the ik state; is your ik solver ignoring orientation?

**Comment by acornacorn** [comment]
The main issue was with the IK.  In the robot where we needed this we had a custom IK solver which would accept position and return joint angles that placed the eef at that position with arbitrary orientation.  Sachin @sachinc may have suggestions about how to create such an IK solver for your robot.

Once you have a set of goal joint angles the planner can plan to that goal.  If I understand correctly, the planner does not care about position and orientation; it just needs a goal in terms of joint angles.

The part I did was to add the style parameter to RobotInteraction::decideActiveEndEffectors() (see moveit_ros/robot_interaction/include/moveit/robot_interaction/robot_interaction.h).  Passing EEF_POSITION will turn off the orientation rings in the interactive marker, so you can change the position but not the orientation.  But this is only cosmetic.  Both position and orientation are still passed to the IK solver.  So to make it work you really need the IK solver to ignore orientation.

-Acorn

**Comment by marioprats** [comment]
I did this once (in the before-MoveIt era) by creating a custom IK solver
with KDL (inheriting from ChainIkSolverVel) and overloading CartToJnt to
compute a new Jacobian where the rows corresponding to the orientation were
set to zero. I guess it would be possible to do the same inside a MoveIt IK
plugin.

**Comment by sachinchitta** [comment]
Position only ik is now configurable directly in moveit if you are using the KDL kinematics solvers. To enable it, you will have to manually edit your kinematics.yaml file. E.g., if your group is named arm, add the following line for (only) that particular group:
position_only_ik: True

This is an experimental feature not yet tested on a variety of robots so please let me know how it works.

**Comment by rguzman1** [comment]
Hi, thank you all for your comments. 

I did test the KDL kinematic solver with the position_only_ik: True, but this gives absolute freedom to the orientation and is not operative to teach the robot localizations. 

I have been able to do some testing creating a custom plugin following the instructions in http://moveit.ros.org/wiki/Kinematics/IKFast and choosing the TranslationDirection5D IK Type from the openrave IK Types. It works, but not very well, it is able to reach wrong configurations, I will probably try a different approach.

**Comment by mikeferguson** [comment]
@rguzman1 Have you tried connecting to the robot over the ROS API with your IKFast plugin? The turtlebot_arm uses a TranslationDirection5D IK plugin, and I found that while it did weird things with the RVIZ plugin, if I was sending move_group action commands outside of RVIZ, everything worked perfectly as expected -- I presume that something funky is going on in the interpretation of the request or response in the RVIZ plugin.

**Comment by rguzman1** [comment]
Hi, no I didn't try that. I will check how it is done from the turtlebot_arm. 

Meanwhile I have been able to solve it hacking the kdl plugin, but I am not sure if this is the right way.

See  : http://www.youtube.com/watch?v=m_oqufE-5gY&feature=youtu.be

**Comment by sachinchitta** [comment]
Do you have a pointer to your hacked version? This is something we should be able to integrate - its just a question of how you manually specify a constraint like this easily but I think we could do it with some yaml parameters.

**Comment by rguzman1** [comment]
You just need to add the following lines in the 

483  bool KDLKinematicsPlugin::searchPositionIK function 

and right after the     

552   int ik_valid = ik_solver_pos_->CartToJnt(jnt_pos_in_,pose_desired,jnt_pos_out_);                     

I have just realized that the planning is not working, but I am not sure this is related with this hack...

```
// Robotnik
ROS_INFO("ik_valid=%d", ik_valid);

if (ik_valid!=0) {
    ik_valid = 0;
    // ROS_INFO("Robotnik : jnt_pos_in_=%f  %f  %f", jnt_pos_in_(0), jnt_pos_in_(1), jnt_pos_in_(2));
    KDL::Frame p_out;
    if (fk_solver_->JntToCart(jnt_pos_in_,p_out) >= 0) {
        KDL::Vector vel = pose_desired.p - p_out.p;
        // Filter vel
        KDL::Vector vel_filter = vel;

        if ((fabs(vel.x())>fabs(vel.y())) && (fabs(vel.x())>fabs(vel.z()))) vel_filter = KDL::Vector(vel.x()*0.05, 0.0, 0.0);
        if ((fabs(vel.y())>fabs(vel.x())) && (fabs(vel.y())>fabs(vel.z()))) vel_filter = KDL::Vector(0.0, vel.y()*0.05, 0.0);
        if ((fabs(vel.z())>fabs(vel.x())) && (fabs(vel.z())>fabs(vel.y()))) vel_filter = KDL::Vector(0.0, 0.0, vel.z()*0.05);
        ROS_INFO("Robotnik : vel_filter =%f   %f   %f ", vel_filter.x(), vel_filter.y(), vel_filter.z() );

        KDL::Vector rot(0,0,0);

        KDL::Twist incr_pos = KDL::Twist(vel_filter, rot);
        // computes joint velocities as a function of the cartesian velocities
        KDL::JntArray jnt_pos_incr;
        jnt_pos_incr.resize(5);
        vel_solver_->CartToJnt(jnt_pos_in_, incr_pos, jnt_pos_incr);

        for (int i = 0; i < 5; i++){
            jnt_pos_out_(i) =  jnt_pos_out_(i) + jnt_pos_incr(i);
            }
        ROS_INFO("Robotnik : jnt_pos_out_ =%f  %f  %f  %f  %f ", jnt_pos_incr(0), jnt_pos_incr(1), jnt_pos_incr(2), jnt_pos_incr(3), jnt_pos_incr(4) );                     
        }

    }
    // fRobotnik
```

**Comment by adamjardim** [comment]
The position only IK command for the kinematics.yaml (position_only_ik: True) really should be documented somewhere.  The only mentions of this as an option are directly in the code and this thread.

**Comment by sachinchitta** [comment]
This is now documented in one of the tutorials: http://docs.ros.org/api/pr2_moveit_tutorials/html/kinematics/src/doc/kinematics_configuration.html
