### ISSUE TITLE
Better separation of front end and backend

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_ros#26]
I'd like to refactor the plugin to preserve more separation of the front end and backend.

I propose to do this by making the plugin itself just a wrapper that maps menu and button events to send messages to a backend node that implements all the functionality currently in planning_display, planning_link_updater, etc.  (This is the way it is done in pr2_interactive_manipulation.)

Since I know you want the user of Rviz to just have to load a single plugin, we can preserve the fact that the plugin currently instantiates other display types within itself. As part of that, I could break the planning_scene_render into a new type of display plugin that the planning plugin instantiates, with the added bonus that one could use a planning scene display separately.

I'm happy to do this, because I think it will be critical for the teleop stuff I am doing. Jon also wants it so that he can instantiate more of the backend functionality from his other code.

**Comment by jonbinney** [comment]
I second this. Having a small plugin that just displays planning scenes would be very useful. And structuring the backend code in a way which is easy to instantiate in other nodes would be very useful.

My use case is for debugging manipulation code. I'd like to be able to instantiate a couple of classes in my manipulation node, and quickly expose parts of the planning process for debugging. The following things would be useful for me:
- from any node, publish multiple planning scenes, each with a different name (for instance the pre-grasp planning scene, the current plannning scene, etc). Then in the rviz planning scene plugin be able to select which one i want to display
- easily instantiate interactive markers for various robot groups, drag the markers around in rviz, and have callbacks called in my node (i think this is mostly in the robot_interaction package already)
- be able to add debugging  lines of code in my nodes that publish things like trajectories, robot poses, results of collision detection, etc. and have these show up in rviz as markers. 

I think a lot of these functionalities are already in the moviet rviz plugin or other packages, but i usually want to use them from my own node and not in the plugin or move_group.

**Comment by isucan** [comment]
I think this is a great idea! Let's do it!
One small request: as you do things, please try to use "git mv" as much as possible, so it is easier for me to merge on top of groovy. Or better yet, if you can develop on top of groovy, just do that.

**Comment by isucan** [comment]
Take a look at what is there now?

**Comment by isucan** [comment]
Closing for now. Please reopen if further work is needed.
