### ISSUE TITLE
ros-planning github org icon

### ISSUE THREAD

**Issue by jbohren** [moveit/moveit_ros#270]
![ros_planning_dots](https://f.cloud.github.com/assets/1253450/720647/e566583a-dfc6-11e2-9c60-5d6252bc6635.png)

**Comment by davetcoleman** [comment]
Sweet!!

**Comment by davetcoleman** [comment]
bump

**Comment by mikeferguson** [comment]
Done, might take a few moments to propagate.

**Comment by davetcoleman** [comment]
hehe, i had forgotten about this. thanks @jbohren !
