### ISSUE TITLE
Increase the minimum end-effector marker size?

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#283]
I spent some time trying to figure out why my end-effector interactive marker was not showing up in rviz, until I realized it was already there but so small that I couldn't see it!

The piece of code related to this is in RobotInteraction::computeGroupMarkerSize (moveit_ros/robot_iteraction/src/robot_interaction.cpp):

```
// if the scale is less than 1mm, set it to default
if (s < 1e-3)
  s = DEFAULT_SCALE;
```

Do you think we could increase this constant to something bigger, 5cm maybe? 
In my case the last link of the group was about 1.3mm in size, and therefore the default scale of 0.2 was not set.

**Comment by isucan** [comment]
Thank you! That is a good point. Fixed.
