### ISSUE TITLE
Is move_group able to handle partial joint_state messages?

### ISSUE THREAD

**Issue by liborw** [moveit/moveit_ros#286]
We are working with dual-arm robot, and the driver sends joint states for each arm separately. As stated [here](http://ros-users.122217.n3.nabble.com/merging-different-joint-states-td2289189.html) the robot_state_publisher should be able to handle this. Does move_group handle this as well?

**Comment by isucan** [comment]
Yes, move_group will split the motion plan and send it to the corresponding controllers. 
Please see this:
http://moveit.ros.org/wiki/Executing_Trajectories_with_MoveIt!

Please feel free to send e-mail to the moveit-users mailing list if you have further questions.

**Comment by isucan** [comment]
And I just realized I read this wrong :) You were talking about joint states, not output trajectories.
Nevertheless, the answer is the same. You can send joint states in multiple messages and this is fine.
Sorry about this!
