### ISSUE TITLE
Duplicate Scene Collision Object

### ISSUE THREAD

**Issue by adamantivm** [moveit/moveit_ros#29]
It would be nice to be able to create a duplicate of an already imported and positioned object in a planning scene.

**Comment by isucan** [comment]
Where would that duplicate be placed? What kind of UI component do you envision for this?

**Comment by adamantivm** [comment]
Probably in the Scene Collision Objects tab, as another button next to
'Import Object', etc.
- Julian

**Comment by isucan** [comment]
I worry this would clutter the interface too much. Unless this is a strong need, I would propose holding on the implementation of this feature for now.

**Comment by adamantivm** [comment]
When creating a realistic planning scene, it is not rare to need to place many objects nearby. For example bins in a shelf, rows of cabinets, etc. It currently takes quite a few clicks and adjustments to import and object and get it in the right position, orientation and scale. Being able to duplicate an object and its properties with a single click seems programmatically very simple and would save a lot of work in creating the scenes. I request reconsidering this functionality. If one more button seems like too much clutter then we can consider a hot key or a menu function at least.
