### ISSUE TITLE
.deb missing file (libmoveit_semantic_world.so)

### ISSUE THREAD

**Issue by diecastzinc** [moveit/moveit_ros#299]
Just updated to latest hydro debs (8/20), and I'm missing libmoveit_semantic_world.so, which is required by the rviz plugin. Looks like ros-hydro-moveit-ros-perception package needs to be added as dependency to -full etc.

[ERROR] [1377124453.758253085]: PluginlibFactory: The plugin for class 'moveit_rviz_plugin/MotionPlanning' failed to load.  Error: Failed to load library /opt/ros/hydro/lib/libmoveit_motion_planning_rviz_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libmoveit_semantic_world.so: cannot open shared object file: No such file or directory)

**Comment by isucan** [comment]
Ouch. Sorry about that. The install rule for the lib is missing. I'll fix it asap.

**Comment by sachinchitta** [comment]
This seems to have been fixed - reopen if you have more issues.
