### ISSUE TITLE
Configure IK Timeout in Kinematics Tool GUI

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#3]
I heard that the default for a non-solution is 5 seconds per point.

If a user is not familiar with their arm, the initial guesses for Workspace size can be defined with many non-solution points.

Allowing the user to change this value would speed preliminary searches and allow much faster searching if the user knows their arm does not contain many degrees of freedom.

**Comment by sachinchitta** [comment]
Now available as a ROS param - "kinematics_solver_timeout" in the launch file - set internally to default to 5.0
