### ISSUE TITLE
Remove Attached Collision Objects from  Moveit Rviz Plugin

### ISSUE THREAD

**Issue by sksellio** [moveit/moveit_ros#30]
Currently you can remove regular unattached collision objects from the planning scene from the "Scene Collision Objects" tab of the moveit_rviz_plugin. It would be good to be able to remove attached collision objects as well.

**Comment by isucan** [comment]
I guess a first step here is to have the option to attach collision objects. How does having an option for objects to be "attached" or "detached"? So you can attach existing objects, detach them, (and can delete them)

**Comment by sksellio** [comment]
That sounds great!
