### ISSUE TITLE
Unnecessary Error Message at Startup

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#303]
Whenever I use MoveIt now I get a red error message in my console:

```
ERROR ros.moveit_ros_visualization: Object recognition action: Unable to connect to action server within allotted time
```

It seems this is just an unused feature and should only be a warning, if that. I tried to make the change myself but I see that it would also mute real errors that could arise within the visualization code in file:

`moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
`

**Comment by isucan** [comment]
I agree. I can fix it at some point. I will not mind a pull request either :)

**Comment by isucan** [comment]
fixed
