### ISSUE TITLE
Mimic joint support broken in latest source

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#307]
Since updating my source install of MoveIt with the latest robot_model and robot_state changes, mimic support seems to have broken. When launching move_group I get:

```
DEBUG ros.moveit_ros_planning: Joint variable 'left_gripper_r_finger_joint' has never been updated
DEBUG ros.moveit_ros_planning: Joint variable 'right_gripper_r_finger_joint' has never been updated
 WARN ros.moveit_ros_planning: The complete state of the robot is not yet known.  Missing left_gripper_r_finger_joint, right_gripper_r_finger_joint
```

Where those two joints worked previously by mimicking their l_finger counterparts.

**Comment by sachinchitta** [comment]
Is this still an issue - I don't see it when I bring up the PR2. Could you please post some way of duplicating this?

**Comment by davetcoleman** [comment]
I am currently publishing the joint manually (worked around it) so I'm not sure if its still an issue, but @isucan at the time told me it was and to post this issue.

**Comment by isucan** [comment]
I fixed this a while ago.
