### ISSUE TITLE
Workspace constraints for manipulation

### ISSUE THREAD

**Issue by sashalambert** [moveit/moveit_ros#312]
It would be nice to have a bounding volume on motion planning over the entire model ex. arm moving in a constrained work cell.

**Comment by davetcoleman** [comment]
A bounding volume workspace for planning already exists in MoveIt - do you mean have it automatically resize to the size of your URDF model?

**Comment by isucan** [comment]
what is missing is that bounding volumes are not imposed unless you are using SE2 / SE3 state spaces. So... you cannot constrain the motion of an end effector, for example.

**Comment by acornacorn** [comment]
Duplicate of https://github.com/ros-planning/moveit_core/issues/93
