### ISSUE TITLE
ros-hydro-moveit-ros-perception is trying to build against ros-hydro-pcl 

### ISSUE THREAD

**Issue by tfoote** [moveit/moveit_ros#314]
http://jenkins.ros.org/view/HbinP32/job/ros-hydro-moveit-ros-planning_binarydeb_precise_i386/38/console

```
ros-hydro-moveit-ros-perception : Depends: ros-hydro-pcl which is a virtual package.
```

This should be a rosdep not a system dependency. I think that this just needs a debian increment with an up to date rosdep.  @wjwwood can you confirm? 

This appears to be breaking all of the moveit hydro debbuilds: http://www.ros.org/debbuild/hydro.html

**Comment by wjwwood** [comment]
No it needs to change it's package.xml to use the new rosdep rule and then be released again, similar to this change:

https://github.com/ros-perception/perception_pcl/commit/8acdf7d38a36ab62ebdc1ed2cf483d6ebc1f9831#L0L22

**Comment by isucan** [comment]
The package actually does not need to depend on pcl, just pcl_conversions. There was a forgotten build dep in package.xml which I have removed, but have not gotten around to re-releasing the debs (trying to fix more things). I am almost done with my fixes though, I'll try to release something new by the time you wake up :)

**Comment by tfoote** [comment]
Awesome! That will get us close to being able to do another hydro sync by fixing the majority of the remaining regressions.

**Comment by davetcoleman** [comment]
oops ignore that reference - not really relevant to this discussion. though we are having pcl issues as well

**Comment by isucan** [comment]
debs seem to have built fine. closing this; please reopen if i missed something
