### ISSUE TITLE
-march=native is probably a bad idea for building debs

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#318]
https://github.com/ros-planning/moveit_ros/blob/hydro-devel/perception/cmake/moveit_find_sse.cmake#L18 sets -march=native, which is going to optimize the build for the CPU found on the buildfarm. This could cause a number of interesting failure modes when the build farm CPU changes, or is different from that installed in the end user's machine.

Is this really needed?

**Comment by isucan** [comment]
Very good point! Thanks!

**Comment by thether** [comment]
Hello,

I'm using Ubuntu 14.04 and installed ROS and moveit form the deb-pkgs.

By starting a launch file using the move_group i get the following error.
`<[move_group-5] process has died [pid 18219, exit code -11, cmd /opt/ros/indigo/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/path/path/.ros/log/25ee088c-3ab3-11e5-8ec9-8056f24ad9c3/move_group-5.log].
log file: /path/path/.ros/log/25ee088c-3ab3-11e5-8ec9-8056f24ad9c3/move_group-5*.log>`

Is it possible that it has to to with this bug?

Where do I have to do the changes mentioned above?
I cant find the mentioned .cmake file..

Thank you,
Carl

**Comment by mikeferguson** [comment]
This bug fix was released into Hydro 2 years ago (before indigo was forked) so it has always been in Indigo.

The crash log above tells us almost nothing. You'll need to provide more info on your setup to get any help. I recommend using the moveit-users mailing list rather than this ticket.

If you installed from debs, there will not be a CMakeLists.txt since everything is already built on the buildfarm.
