### ISSUE TITLE
Segmentation fault in Rviz plugin?

### ISSUE THREAD

**Issue by Lennartm** [moveit/moveit_ros#319]
When adding a Motion planning visualization rviz crashes. With planning scene also.  Running Hydro on Ubuntu 12.04 32 bit.

roslaunch pr2_moveit_config moveit_rviz.launch debug:=true

```
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0xa6240b40 (LWP 18292)]

Program received signal SIGSEGV, Segmentation fault.
0xb63fa092 in QMetaType::construct(int, void const*) () from /usr/lib/i386-linux- gnu/libQtCore.so.4
```

**Comment by davetcoleman** [comment]
This is the same issue as mine
https://github.com/ros-visualization/rviz/issues/690

**Comment by isucan** [comment]
Please reopen if this is not the same bug (aka, things do not work after removing devel/ and build/)
