### ISSUE TITLE
move visualization to a new repository?

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#321]
I noticed the other day, that if doing a source install, moveit_ros effectively requires rviz to be installed, due to the plugins found within that repository.

Throughout the history of ROS, it has generally been advised to have visualization in a separate set of packages/repositories as many/most robots don't have graphical interfaces and the dependencies can be quite large to install (imagine installing all of X on a robot that has no screen, just so you can plan...)

**Comment by isucan** [comment]
I wonder, is it possible to have a variant of installing from source that disables some packages? I understand the visualization dependencies issue, but I'd rather not have to have a separate repo. It would be great if we had a tool that checks out a particular package from a repo? @dirk-thomas ?

**Comment by mikeferguson** [comment]
Yeah, I'm not sure. Either way, this one is not critical to me (since my robots do have a graphical interface available), I was just pointing it out as a possible improvement for anyone whom that is not the case.

**Comment by dirk-thomas** [comment]
If you do use the rosinstall_generator which provides you with the last _released_ sources of each package you only get the packages you asked for - not complete repositories. It operates on released stuff only and not on development branches what is a good idea imo. You only want very specific packages/repos from their development branch.

If you still want to check out the development branch of a repo but do not want all the packages inside you can either drop CATKIN_IGNORE files into the packageswhich you want to skip or consider splitting the repo. Checking out parts of a git repo is nothing which you wanna do.

**Comment by isucan** [comment]
I am happy with Dirk's suggestions on this. Do you think we can close the issue for now?

**Comment by mikeferguson** [comment]
yup
