### ISSUE TITLE
Found contact between object and robot attached (of same name)

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#323]
Pick and place is aborted due to this:

```
[ INFO] [1380532200.119553897]: Attaching world object 'the_object' to link 'gripper_link'
[ INFO] [1380532200.119951273]: Attached object 'the_object' to link 'gripper_link'
[ INFO] [1380532200.122516532]: Trajectory component 'retreat' is invalid
[ INFO] [1380532200.124162277]: Found a contact between 'the_object' (type 'Object') and 'the_object' (type 'Robot attached'), which constitutes a collision. Contact information is not stored.
[ INFO] [1380532200.124211867]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1380532200.131468313]: Trajectory component 'retreat' is invalid
[ INFO] [1380532200.133381279]: Found a contact between 'the_object' (type 'Object') and 'the_object' (type 'Robot attached'), which constitutes a collision. Contact information is not stored.
[ INFO] [1380532200.133405351]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1380532200.133448003]: Stopping execution because the path to execute became invalid (probably the environment changed)
```

running off hydro-devel

**Comment by mikeferguson** [comment]
@isucan any ideas on this one?

**Comment by isucan** [comment]
I am guessing the attached object is not detached correctly. Or not checked in a correct planning scene. @davetcoleman is having the same problem. I will look at this today.

**Comment by mikeferguson** [comment]
Awesome! Let me know if you have something you want me to test.

**Comment by davetcoleman** [comment]
+1 indeed.

**Comment by mikeferguson** [comment]
@davetcoleman If you need a temporary work around, I'm doing this: https://github.com/mikeferguson/moveit_core/commit/bcd0283eddc62f58aabb5748d3d6c371a91a133a

Somehow, I got this bug to go away on my home computer -- but on my robots and work computer it remains even after doing what I thought fixed it at home.... anyways, in the meantime I'm using the hacky patch above.

**Comment by mikeferguson** [comment]
A few notes from walking through the code and rqt_console outputs:

We touch https://github.com/ros-planning/moveit_core/blob/hydro-devel/planning_scene/src/planning_scene.cpp#L1371 which means that we indeed found the collisiion object in the wolrd, and (in theory) removed it.

We also touch https://github.com/ros-planning/moveit_core/blob/hydro-devel/planning_scene/src/planning_scene.cpp#L1461 which means that we attached it...

**Comment by mikeferguson** [comment]
@isucan, I have two catkin workspaces on my home machine -- one of them exhibits this problem, the other does not.. my workspace at work does exhibit this problem. I have cleaned out each workspaces devel/build and rebuilt them, but I can't seem to figure out the difference between the workspace that works, and all the other. Logically the code seems correct after a read through...

**Comment by isucan** [comment]
I fixed some problems related to this a few days ago. The obvious question is, are you sure you have the same checkout of all repos on both machines and there are no debs installed (just in case)?
I have seen this type of behaviour when retying pick&place actions without restarting move_group. My test code for example is publishing an object, and my previous run completed pick successfully, but not place. So I could have a stale attached object and a new collision object with the same name. I am wondering whether synchronization could play a role here. On the machine that does not work, do you get the exact same failure always? Is it a slower machine?

**Comment by mikeferguson** [comment]
Ok, on both machines, I removed all ros-hydro-moveit-\* packages, did a clean check out of hydro-devel of moveit_ros, moveit_core, moveit_planners, moveit_msgs, moveit_plugins. All of the ROS debs on the system are the latest in shadow-fixed.

The failure is always the same: the pick starts, pregrasp is ok, approach is ok, grasp is ok, retreat gets aborted:

```
[ INFO] [1380693570.818046152]: Planning attempt 1 of at most 1
[ INFO] [1380693570.818229895]: Added plan for pipeline 'pick'. Queue is now of size 1
[ INFO] [1380693570.931537076]: Attaching world object 'the_object' to link 'gripper_link'
[ INFO] [1380693570.931596058]: Attached object 'the_object' to link 'gripper_link'
[ INFO] [1380693571.027013031]: No planner specified. Using default.
[ INFO] [1380693571.027111488]: LBKPIECE1: Attempting to use default projection.
[ INFO] [1380693571.031536086]: LBKPIECE1: Starting with 1 states
[ INFO] [1380693572.188107193]: LBKPIECE1: Created 47 (27 start + 20 goal) states in 35 cells (24 start (24 on boundary) + 11 goal (11 on boundary))
[ INFO] [1380693572.188156615]: Solution found in 1.160996 seconds
[ INFO] [1380693572.197872396]: Path simplification took 0.009640 seconds
[ INFO] [1380693572.267583167]: Found successful manipulation plan!
[ INFO] [1380693572.267721979]: Pickup planning completed after 1.449597 seconds
[ INFO] [1380693575.380219755]: Attaching world object 'the_object' to link 'gripper_link'
[ INFO] [1380693575.380356055]: Attached object 'the_object' to link 'gripper_link'
[ INFO] [1380693575.385440657]: Trajectory component 'retreat' is invalid
[ INFO] [1380693575.389659631]: Found a contact between 'the_object' (type 'Object') and 'the_object' (type 'Robot attached'), which constitutes a collision. Contact information is not stored.
[ INFO] [1380693575.389704192]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1380693575.398466412]: Stopping execution because the path to execute became invalid (probably the environment changed)
[ INFO] [1380693575.398534354]: MoveitSimpleControllerManager: Cancelling execution for arm_with_torso_controller
[ INFO] [1380693575.398614752]: Stopped trajectory execution.
```

Afterwards, the object is definitely attached, and is definitely removed from the collision world, because if you try to rerun the pick:

```
[ERROR] [1380694394.765595061]: Attempting to attach object 'the_object' to link 'gripper_link' but no geometry specified and such an object does not exist in the collision world
```

All of these machines are 3rd gen i7 processors. It would seem to me that there must be some sort of race condition -- how/where exactly is collision checking called? The same thread, a different one?

**Comment by isucan** [comment]
@mikeferguson I am not sure where this was left off. Did this go away when rebuilding?

**Comment by mikeferguson** [comment]
@isucan, have not been able to make this go away (the one time it went away appears to have been some sort of fluke). Currently still using my hack above, but I haven't really put any time into this right now. Will have more time to look at it after the 25th

**Comment by awesomebytes** [comment]
Hello, just reporting I find the same behaviour (collision with same name object). I'm working with debs right now.

**Comment by lindzey** [comment]
For those of you still with this issue (@awesomebytes , @davetcoleman, @mikeferguson), how are you calling the Pickup command? I saw this behavior when using the Pickup actionlib interface when I'd forgotten to set:

```
    pickup_goal.planning_options.planning_scene_diff.is_diff = True
    pickup_goal.planning_options.planning_scene_diff.robot_state.is_diff = True
```

**Comment by awesomebytes** [comment]
I set those as True, here you have an example of a message I sent: http://pastebin.com/wnD3H8e8
But it happens anyways.

**Comment by mikeferguson** [comment]
So, is_diff being true appears to make this fixed for me on all of our robots that i've tested.

**Comment by mikeferguson** [comment]
This is fixed for me, closing.

**Comment by jonbinney** [comment]
Argh, this one bit me again today. Having to set `planning_scene_diff.is_diff` to true because it defaults to false is always going to be counter intuitive. This would be a pain to change now, but if the moveit messages ever get reworked at some point, I'd suggest : 
- rename `PlanningOptions.planning_scene_diff` to `PlanningOptions.planning_scene`
- move the `is_diff` option outside of the planning scene message itself, and call it `planning_scene_is_diff`

Not calling it "planning_scene_diff" would at least make it clearer that it defaults to overwriting the current planning scene.

Edit: fixed a couple typos

**Comment by jonbinney** [comment]
This would also be a good use case for default values that aren't necessarily the language defaults for that type. (for example in ROS 2?) :-)

**Comment by davetcoleman** [comment]
@jonbinney Maybe you could add your above synopsis and warning to developers in the [PlanningScene.msg](https://github.com/ros-planning/moveit_msgs/blob/jade-devel/msg/PlanningScene.msg). Like a big warning at the top in the comments.

**Comment by jonbinney** [comment]
@davetcoleman good call; I'll do that.

**Comment by jonbinney** [comment]
On closer inspection, I think the problem is that I was using the ApplyPlanningScene service, which repsects the `is_diff` variable and therefor overwrites any existing planning scene. Pick and place, on the other hand, ignores `planning_scene_diff.is_diff` member and always treats that scene as a diff: 
https://github.com/ros-planning/moveit_ros/blob/2335765420e97cb9ddf816590bd1907ddc03e471/manipulation/pick_place/src/pick.cpp#L229

So really, `is_diff` shouldn't be inside of the PlanningScene message because it is sometimes ignored and sometimes not, depending on the context. But that can't be helped right now.

**Comment by rhaschke** [comment]
> So really, |is_diff| shouldn't be inside of the PlanningScene message 
> because it is sometimes ignored and sometimes not, depending on the 
> context. But that can't be helped right now.
> I would conclude, that `is_diff` should be always considered.

**Comment by jonbinney** [comment]
@rhaschke that would also be a good way to go. But then `PlanningOptions.planning_scene_diff` would have to be renamed to avoid extreme confusion (since it wouldn't be a "diff" by default)

**Comment by v4hn** [comment]
> Pick and place, on the other hand, ignores planning_scene_diff.is_diff member and always treats that scene as a diff

I agree with @rhaschke, `is_diff` should _always_ be respected. If anything, we could rename the flag to `is_full_scene` in kinetic, so that the default is more reasonable. But this is such a fundamental change, that I will likely never happen.

As a more reasonable way to address your problem @jonbinney, I would propose to add an error message (& failure?) to all interfaces that use the `PlanningOptions` message if they receive a `planning_scene_diff` message with `is_diff` set to false.
The field in the `PlanningOptions` is called `planning_scene_diff`, so in my opinion the specification is violated if a full scene is specified in there.

**Comment by rhaschke** [comment]
+1

**Comment by jonbinney** [comment]
@v4hn an error in pick and place when `planning_scene_diff.is_diff` is set to `false` would definitely be an improvement. It seems like there are legitimate use cases where someone would want to send a full planning scene to pick and place rather than just sending a diff though, right?

**Comment by v4hn** [comment]
These legitimate use cases still work if either `move_group` maintains an empty planning scene before sending the request or by explicitly subtracting problematic objects from the scene.
