### ISSUE TITLE
IK Solver does not search alternative solutions when in collision 

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#33]
Not sure if this is a bug, or just not implemented for any reason: when you move the end-effector around and some links of the robot are in collision, I would expect the IK solver to find another collision-free solution in the space of redundant configurations.

**Comment by isucan** [comment]
I guess I should do this at some point :) I'll let you know. Thanks for reminding me!

**Comment by mateiciocarlie** [comment]
Sorry, just learning this interface and figuring out how to "watch" the thread, closed the issue by mistake.

**Comment by isucan** [comment]
@sachinchitta says we should keep it as it is by default. I added a bit of functionality that should allow searching for valid states. Not sure how to make it available in a convenient way. Any suggestions?

**Comment by mateiciocarlie** [comment]
So then whether you get a solution or not is an artifact of the seed you happen to choose?

In general, at least trying multiple seeds is something that I feel we will absolutely need. Whether that sits in the IK itself or in a wrapper around it, both seem like feasible options.

**Comment by marioprats** [comment]
What about a new checkbox property? when activated search for alternative
solutions if there is a collision. If not activated show the default
behavior.

**Comment by isucan** [comment]
Right now we use as seed the previous state of the arm, to avoid having the arm jump around as we drag the end effector. Random seeds are used if IK fails with that first seed. However, we do not look for alternatives (currently) if IK is successful but the state is in collision.
The checkbox suggestion seems reasonable to me.

**Comment by mateiciocarlie** [comment]
Checkbox idea is fine to me as well. But where in the backend will that go? 

We'll need this functionality for the benchmarking work as well, given we'll be using gripper poses as goals. Oh, wait - is that all taken care of by the sampling-based planner? How does that work - do you run the sampling based planner with gripper space constraints, or do you do IK first and then plan to joint space goal?

**Comment by isucan** [comment]
The call to IK stuff will be in the rviz plugin itself. The IK functionality we use is from KinematicState. 

The planners use a notion of constraint samplers -- the constraint_samplers library which spawn threads that generate valid states in parallel, while a planner is running. As part of sampling constraints, if we happen to constrain a link (position, or orientation, or both) that is the tip of a chain and we happen to have declared an IK solver for that, IK solvers are also instantiated. I don't the benchmarking should worry about this functionality.

**Comment by isucan** [comment]
fixed in 775f115ae4260b9451a9a640d668091565d25275
