### ISSUE TITLE
Duplicate header in kdl plugin.

### ISSUE THREAD

**Issue by davidkotfis** [moveit/moveit_ros#345]
kdl_kinematics_plugin.h includes the same header file twice:

<moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp>

**Comment by davetcoleman** [comment]
Which header?

**Comment by dkotfis** [comment]
In moveit_ros/planning/kdl_kinematics_plugin/include/moviet/kdl_kinematics_plugin/kdl_kinematics_plugin.h

On hydro-devel -> lines 59 and 61 both include chainiksolver_pos_nr_jl_mimic.hpp.
(Lines 60 and 62 on groovy-devel)

Not a big deal... just something I noticed.

**Comment by acornacorn** [comment]
fixed in https://github.com/ros-planning/moveit_ros/pull/360
