### ISSUE TITLE
move_group_interface should support multiple goals

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_ros#35]
move_group_interface should support multiple pose goals:
(1) for one end-effector
(2) for multiple end-effectors

**Comment by isucan** [comment]
Can you be a little more specific about this? I am assuming you mean for something like you construct a group for a group like 'arms' and there are multiple end-effectors there, and you would like to specify their pose. Please correct me if you have something else in mind.

**Comment by sachinchitta** [comment]
Say you have just one end-effector - right_gripper attached to right_arm. It should be possible to use move_group_interface to give it a vector of possible end-effector goals. This gets passed down into the planner which would return a plan to one of them which would then get executed.

Similarly, it should be possible to send a vector of possible goals for multiple end-effectors with the assumption that each end-effector would get the same number of goals. Corresponding goals would be paired up.

**Comment by isucan** [comment]
got it. will do.
