### ISSUE TITLE
move_group (package moveit_ros_move_group) segfaults under both Groovy and Hydro (Ubuntu 12.10)

### ISSUE THREAD

**Issue by MITMERS** [moveit/moveit_ros#369]
Hi,

I'm getting a segmentation fault every time I try to run the "move_group" binary in the "moveit_ros_move_group" package under Hydro. When I switch to Groovy, the program starts fine (I'm using it along with the "baxter_moveit_config" package to control a Baxter robot), but crashes every time I try to use the MoveGroup to send it a new goal. The exact same code runs perfectly fine on another machine running Ubuntu 12.04. Also, I get a compilation warning on 12.10 involving the C++ Eigen library that I don't get on 12.04 when I include the "move_group.h" header. Could it be the case that there is an incompatibility issue between versions of Eigen that is causing move_group to crash during run-time?

By the way, I installed all ros-<distro>-moveit packages and Eigen using apt-get. I've also upgraded them to the latest version, but the problem persisted.

**Comment by acornacorn** [comment]
Are you using 32-bit or 64-bit Ubuntu?  There are known issues with 32-bit.
Some problems may have been fixed by
https://github.com/ros-planning/moveit_core/commit/64353d5b7d4f4523fc101cee2a847ce9d6dd3b85
in the hydro sourcecode.

**Comment by isucan** [comment]
This is likely the 32bit problem. Please reopen if it is still an issue.
