### ISSUE TITLE
Run reachability benchmark end-to-end on test scene

### ISSUE THREAD

**Issue by mateiciocarlie** [moveit/moveit_ros#38]
This shows that we can run the benchmark defined in #36 end-to-end. It needs:
- the appropriate features in the benchmarking tool (#36)
- the appropriate feature in the rviz plugin (#37)
- one demo set of panning scenes (potentially containing a single scene) and a set of gripper poses defined in it. Do not worry too much about the exact scene, this is just to show that the end-to-end pipeline is operational.

Success criteria:
- we can run the benchmark and get numerical scores for at least two different arms.

helping: @adamantivm @isucan

**Comment by isucan** [comment]
It would be nice if we can use the warehouse tool for initializing a demo database to generate this demo benchmark too.

**Comment by mateiciocarlie** [comment]
Is the warehouse tool different from the rviz plugin? My thought was that we'd use the rviz plugin to populate the database with what we need for the demo benchmark, just as we would for the actual scenes to be used in the real benchmarks.

**Comment by isucan** [comment]
The warehouse tool as it was in arm_navigation is no longer there -- the rviz plugin replaces it. However, there is backed functionality for dealing with the warehouse (just a library). That library also includes a demo app that generates a simple database (command line). I was thinking that it would be nice if we could also have a demo benchmark tool using this demo db, so we can run a demo without having to set up proper planning scenes. This is low priority though.

**Comment by marioprats** [comment]
Feasible!!

**Comment by mateiciocarlie** [comment]
Awesome!!

Can we get a few details? 
- which scene was this run on
- both arms?
- what was the exact config file
- how long did it take

**Comment by marioprats** [comment]
I run it on the 'shelf table tight' with two arms, and just one goal so it was a few seconds. I'll send you the config file by email

**Comment by mateiciocarlie** [comment]
As per @adamantivm 's good suggestion, re-opening this until the result parsing tool in #69 is also complete, at which point we'll get human readable results of the type "Arm A can reach 45% poses, Arm B can reach 23% or something like that"

**Comment by marioprats** [comment]
I'm closing this ticket since this is already working
