### ISSUE TITLE
Configure FK Computation in Kinematics Tool GUI in terms of Time or Samples

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#4]
I loaded a simple 3 dof arm into the tool and allowed it to compute FK for around 1 second. This generated 600,000 points that immediately locked up my computer when RVIZ attempted to visualize that number.

It should be possible to define the stopping point of the computation in terms of either overall 'Allowed Time for Computation' or 'Maximum Output Samples' (default around 1000?). This should help control an unexpectedly taxing output for users with simpler arms.

**Comment by sksellio** [comment]
There's a roslaunch parameter for maximum number of fk points. The default value is currently 5000.

**Comment by chadrockey** [comment]
This should be exposed through the GUI as well.

**Comment by sksellio** [comment]
Chad wants it exposed in the GUI.

**Comment by sachinchitta** [comment]
This tool is now deprecated and being replaced by the workspace GUI and associated functionality.
