### ISSUE TITLE
Split planning_scene_display into separate rviz display plugin

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_ros#40]
Ioan and I have discussed this as a lower-priority item, but I wanted to note it here so we don't forget.
At some point, it would be good to make the planning_scene_display its own rviz display plugin, and then have the motion planning plugin just instantiate one internally.

This has the benefit of allowing someone to display a planning scene without needing the whole motion planning plugin, and could also easily allow multiple planning scenes with different topics to be displayed by just creating multiple displays.

**Comment by isucan** [comment]
Thanks Adam! I had not forgotten -- I almost started working on it today :)

**Comment by isucan** [comment]
done
