### ISSUE TITLE
set default padding and scale for each robot link

### ISSUE THREAD

**Issue by k-okada** [moveit/moveit_ros#402]
default_robot_padding parameter enable users to set default padding value for all links in the robot, But sometimes we'd like to set padding value for each link.

For example, we'd like to set 'padding' in order to avoid self collision between right and left gripper, or gripper and base module of the robot. If we set padding value (say 2cm) for all link, that works for detecting collision between base and gripper, but it also find collision between forearm and upperarm. So we'd like to set small padding value for all link but large value on base or gripper.

One possibility is to add new parameter such as

```
default_robot_link_unpadded_padding: {RARM_JOINT5_Link: 0.05, WAIST_Link: 0.10}
default_robot_link_padding: {RARM_JOINT5_Link: 0.05, WAIST_Link: 0.10}
```

to set padding value for each joint, please check #341 for explanation

**Comment by isucan** [comment]
Since #404 was merged, is that a satisfactory fix?

**Comment by k-okada** [comment]
> is that a satisfactory fix?

Ok, thanks.
