### ISSUE TITLE
separate trajectory display from motion planning display

### ISSUE THREAD

**Issue by acornacorn** [moveit/moveit_ros#419]
Most of MotionPlanningDisplay requires move_group to be running to be useful.  But trajectory display is used in several places (tutorials) where move_group does not run.  This results in error messages about move_group not running. We don't want to remove these errors because they are useful.

Solution: split the TrajectoryDisplay into a separate plugin that can be used standalone.  The MotionPlanningDisplay can also incorporated the TrajectoryDisplay (as a member).

**Comment by hersh** [comment]
+100.  I have wanted this before and think it makes a lot of sense.

Then after it's separated out, let's improve the UI to add more playback controls: stop/start/pause/seek like in a video.  I have often wanted to see just exactly where the had was part-way through the trajectory, but I had the choice only of watching the loop over and over, slowing it down to a crawl and waiting for it to get to my spot, or looking at an all-at-once trace display that is hard to see through to the detail I want.

**Comment by isucan** [comment]
++1 as well. I have wanted this in the past too. This would be great to
have!

**Comment by davetcoleman** [comment]
+1 I've had similar thoughts. 

Related thought, perhaps the choice of which planning group to plan for should be moved into the main tabbed UI component of the Rviz plugin, rather than in the properties of the MotionPlanningDisplay. Sorry if this is too unrelated.

**Comment by mikeferguson** [comment]
implemented in #551
