### ISSUE TITLE
Allow namespacing moveit::planning_interface::MoveGroup instances

### ISSUE THREAD

**Issue by adolfo-rt** [moveit/moveit_ros#421]
Currently, there is no way to connect multiple `moveit::planning_interface::MoveGroup` instances to different move_group servers from within the same ros node. This is because the [action clients](https://github.com/ros-planning/moveit_ros/blob/hydro-devel/planning_interface/move_group_interface/src/move_group.cpp#L126) are created without specifying the NodeHandle on top of which we want to namespace them. A usecase where this would be needed would be that of sending planning requests to different robots, each living in its own namespace. Note that it _is_ currently possible to create multiple `moveit::planning_interface::MoveGroup` instances, each associated to a different planning group of the _same_ move_group server.

The above argument applies for the rest of the ROS API ([services](https://github.com/ros-planning/moveit_ros/blob/hydro-devel/planning_interface/move_group_interface/src/move_group.cpp#L135-L137), [publishers](https://github.com/ros-planning/moveit_ros/blob/hydro-devel/planning_interface/move_group_interface/src/move_group.cpp#L121-L122)), which use the default-constructed [node_handle_](https://github.com/ros-planning/moveit_ros/blob/hydro-devel/planning_interface/move_group_interface/src/move_group.cpp#L956).

I suggest adding an additional NodeHandle member to the [MoveGroup::Options](https://github.com/ros-planning/moveit_ros/blob/hydro-devel/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h#L67) struct, and assign it to the [node_handle_](https://github.com/ros-planning/moveit_ros/blob/hydro-devel/planning_interface/move_group_interface/src/move_group.cpp#L956) member.

**Comment by jbohren** [comment]
This is complete now, right?
