### ISSUE TITLE
Unable to find resource access-denied.dae

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#43]
Probably there is something wrong in my environment, but in groovy the moveit_rviz_plugin cannot find the resource 'access-denied.dae' when the eef is outside the reachable workspace. I see it only exists in the src robot_interaction package, and never installed. Could it be installed under install/share/moveit_ros_planning_interface? I did that as a temporary solution. If it is correct I can submit a pull request.

**Comment by isucan** [comment]
I think that is correct. Thanks for fixing!

**Comment by isucan** [comment]
@marioprats fixed this
