### ISSUE TITLE
Deadlock race condition in MeshFilterBase.

### ISSUE THREAD

**Issue by skuna** [moveit/moveit_ros#444]
When `MeshFilterBase::filter()` is called in one thread and `MeshFilterBase::addMesh()` or `MeshFilterBase::removeMesh()` are called in another thread and got the `meshes_mutex_` before the `MeshFilterBase::doFilter()` job actually started (and got the `meshes_mutex_`) all threads will hang because `MeshFilterBase::doFilter()` waits for the `meshes_mutex_` and `MeshFilterBase::addMesh()` or `MeshFilterBase::removeMesh()` will wait for their helper jobs that won't get executed until `MeshFilterBase::doFilter()` finishes.

As all jobs will be executed in sequence there is no need for mutual exclusion of adding/removing meshes and filtering meshes. The additional computations in `MeshFilterBase::addMesh()` and `MeshFilterBase::removeMesh()` also doesn't affect the filtering itself. `MeshFilterBase::doFilter()` just needs a mutex for consistent call of the `transform_callback_`. So a reasonable fix for this looks as follows:

```
diff --git a/perception/mesh_filter/include/moveit/mesh_filter/mesh_filter_base.h b/perception/mesh_filter/include/moveit/mesh_filter/mesh_filter_base.h
index 8d13e07..83be5e2 100644
--- a/perception/mesh_filter/include/moveit/mesh_filter/mesh_filter_base.h
+++ b/perception/mesh_filter/include/moveit/mesh_filter/mesh_filter_base.h
@@ -247,6 +247,9 @@ class MeshFilterBase
     /** \brief mutex for synchronization of updating filtered meshes */
     mutable boost::mutex meshes_mutex_;

+    /** \brief mutex for synchronization of setting/calling transform_callback_ */
+    mutable boost::mutex transform_callback_mutex_;
+
     /** \brief indicates whether the filtering loop should stop*/
     bool stop_;

diff --git a/perception/mesh_filter/src/mesh_filter_base.cpp b/perception/mesh_filter/src/mesh_filter_base.cpp
index ba4a14a..862ad0e 100644
--- a/perception/mesh_filter/src/mesh_filter_base.cpp
+++ b/perception/mesh_filter/src/mesh_filter_base.cpp
@@ -165,7 +165,7 @@ void mesh_filter::MeshFilterBase::setSize (unsigned int width, unsigned int heig

 void mesh_filter::MeshFilterBase::setTransformCallback (const TransformCallback& transform_callback)
 {
-  mutex::scoped_lock _(meshes_mutex_);
+  mutex::scoped_lock _(transform_callback_mutex_);
   transform_callback_ = transform_callback;
 }

@@ -301,7 +301,7 @@ void mesh_filter::MeshFilterBase::filter (const void* sensor_data, GLushort type

 void mesh_filter::MeshFilterBase::doFilter (const void* sensor_data, const int encoding) const
 {
-  mutex::scoped_lock _(meshes_mutex_);
+  mutex::scoped_lock _(transform_callback_mutex_);

   mesh_renderer_->begin ();
   sensor_parameters_->setRenderParameters (*mesh_renderer_);
```

**Comment by cheffe112** [comment]
This can be closed now because it was fixed in https://github.com/ros-planning/moveit_ros/pull/445.
