### ISSUE TITLE
PR2 Kinematics Test Failing

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#450]
There is a difficult bug that I have so far been unsuccessful fixing. I probably just need to step away from the problem for a bit.
@sachinchitta describes the bug caused by the non-chain kinematics plugin https://github.com/ros-planning/moveit_ros/pull/431#issuecomment-40770238

I worked on fixing it and isolated the problem to [this simple test script](https://github.com/davetcoleman/moveit_pr2/blob/kinematic-bug-test/pr2_moveit_tests/kinematics/src/dave_test.cpp). You can recreate the error by checking out this [branch](https://github.com/davetcoleman/moveit_pr2/tree/kinematic-bug-test), building, then running `rosrun pr2_moveit_tests dave_test`

**The Problem**
Somehow, after initializing a kinematics plugin for the PR2, when you call `getTipFrame()` it tries to re-initialize the plugin by calling the default `virtual bool initialize()` function in kinematics_base.h. I have no idea how it is jumping from one call to another, and `gdb` is not helping. I must be really missing something stupid. @isucan

**Comment by hersh** [comment]
The only times I have seen this type of behavior is when two pieces of .cpp code are run together which have been compiled with different versions of a .h file.  Then the symbol tables will not match up, so a call to function A from one .cpp file will become a call to function B in the other .cpp file.

In this case, it sounds like you have not recompiled all of moveit with your new version of kinematics_base.h.  Or perhaps you _have_ recompiled the right things but are accidentally using an old version which is installed in /opt/ros/hydro or a chained catkin workspace or something.

You can check versions of libraries by doing
`nm -CD libmoveit_whatever.so | less`
and looking for some function signature that is different between the two versions.

**Comment by davetcoleman** [comment]
Thanks @hersh, that was exactly my issue. I have ROS built from source and it recently pulled in moveit repos when I was adding dependencies. 

Now I can't seem to find the issue @sachinchitta was having with the tests. There was one unloading issue with the test that seemed to be caused by using the old, deprecated class loader method. I have fixed there [here](https://github.com/ros-planning/moveit_pr2/pull/49).

My test was the following:
moveit_core branch _kinematic_base_non_chains_
moveit_pr2 branch _pr2_plugin_fixes_

Build all tests:

```
catkin_make run_tests
```

Run the two we are concerned about:

```
rostest pr2_moveit_tests pr2_plugin_test.launch
rostest pr2_moveit_tests kdl_plugin_test.launch
```

Both say 

```
SUMMARY
 * RESULT: SUCCESS
 * TESTS: 4
 * ERRORS: 0
 * FAILURES: 0
```

**Comment by mikeferguson** [comment]
@davetcoleman all test are passing for moveit_ros in Indigo (http://jenkins.ros.org/job/devel-indigo-moveit_ros/) -- can we close this?

**Comment by davetcoleman** [comment]
Seems so
