### ISSUE TITLE
"everyone is happy" message is misleading

### ISSUE THREAD

**Issue by jbohren** [moveit/moveit_ros#454]
```
All is well! Everyone is happy! You can start planning now!
```

Often when bringing up moveit, I see the above message, but there are some failures which can still happen which can prevent _execution_, if not planning. It might be worth adding some checks and a similar "you can start executing now" if the following are true:
- controller manager connected
- at least one controller connected
- at least one controller which can control each motion planning group
- command topic connected

**Comment by davetcoleman** [comment]
Agreed

**Comment by ZdenekM** [comment]
+1

**Comment by v4hn** [comment]
+1 Also, I often encounter long error outputs and somewhere in between it says "All is well! Everyone is happy!".
Well.. That's just not true _by far_ most of the time...
I'd like to remove that part of the message entirely.

**Comment by davetcoleman** [comment]
> I'd like to remove that part of the message entirely.

+1 This is certainly the easiest solution, but perhaps it should only be done in Indigo or newer so as to not confuse the large hydro user base.

**Comment by Kukanani** [comment]
Here we are in Indigo and the message still persists. Can it be removed?

**Comment by atenpas** [comment]
+1

**Comment by v4hn** [comment]
+1 it would be nice if some developer could _finally_ get rid of this message...

**Comment by alainsanguinetti** [comment]
Actually I'm fine with this message, because it fits with the loosely connected nature of ROS systems. It will only fails if at the precise moment something required is not present.
