### ISSUE TITLE
"Self-filtering may fail" because of missing waitForTransform

### ISSUE THREAD

**Issue by mintar** [moveit/moveit_ros#465]
I keep sporadically getting errors like this when using the DepthImageOctomapUpdater:

```
Transform error: Lookup would require extrapolation into the future.  Requested time 1401446451.006236446 but the latest data is at time 1401446450.937553891, when looking up transform from frame [katana_motor2_lift_link] to frame [kinect_rgb_optical_frame]
[ERROR] [1401446451.007936297]: Transform cache was not updated. Self-filtering may fail.
```

This message originates from [depth_image_octomap_updater.cpp:285](https://github.com/ros-planning/moveit_ros/blob/hydro-devel/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp#L285). It looks to me as if there was a `waitForTransform()` missing in [planning_scene_monitor.cpp:818](https://github.com/ros-planning/moveit_ros/blob/56c1b9465fd86795baaff3fb94746e57aeb09ddb/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L818): When `lookupTransform()` is called with the time stamp from the the DepthImage, sometimes the TF buffer for that time isn't filled yet (in this case, it is 0.07 seconds behind), thereby triggering a race condition.

The Katana arm I'm working with can only publish joint states at 25 Hz, so maybe that's why this race condition happens more frequently than with other robots.

**Comment by mintar** [comment]
BTW, I'm on Hydro on Precise, using the latest Moveit binary debs.

**Comment by davetcoleman** [comment]
I always get that error too, with Baxter, and am interested in fixing it as
well.

**Comment by mintar** [comment]
It _probably_ isn't hard to fix: as I wrote, all it needs is probably a few strategically placed `waitForTransform()`s in `planning_scene_monitor`. However, I'm out of office for the next couple of months, so I can't do it myself. Also, we should make sure that we don't build up a long queue of unprocessed messages when lots of `waitForTransform()`s time out in sequence (for example, if the TF publisher is on holiday for a long time). I guess we really only want to wait if we're not already more than 0.1 - 0.2 seconds behind "now" (and that delay should probably be a parameter). Still sounds like a doable pull request (_wink_).

**Comment by jbohren** [comment]
See #540 for a fix

**Comment by arpit15** [comment]
I am using Moveit in Indigo and ubuntu 14.04. I am still getting an error on similar lines.
`[ERROR] [1492050356.981666496]: Transform error: Lookup would require extrapolation into the future.  Requested time 1492050356.311039301 but the latest data is at time 1492050308.434982148, when looking up transform from frame [head] to frame [camera_rgb_optical_frame]
[ERROR] [1492050356.981708685]: Transform cache was not updated. Self-filtering may fail.`
I manually checked for the commits mentioned on this thread. All the changes are there in the moveit version I am using. 
I am trying to use realsense_camera with the baxter_gripper.launch file. My yaml file is [here](https://gist.github.com/arpit15/addd50baee142265abca3fa42f89e4d8) and my baxter_moveit_sensor_manager.xml is [here](https://gist.github.com/arpit15/9c06e444df78989f4a3d616249db0370)

**Comment by arpit15** [comment]
The error was because of constant time difference between my system and baxter. I manually changed the time of my system to match that of baxter to fix the problem.
