### ISSUE TITLE
Move 'Planned Path' Rviz display out of 'MotionPlanning' plugin

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#478]
The package `moveit_ros_visualization` has separate plugins for 'Planning Scene' and 'RobotState' but not 'PlannedPath'. Is there a particular reason behind this other than no one got around to it? It would be nice to show robot trajectories without using the whole heavy-weight plugin (I don't use most of its features).

**Comment by hersh** [comment]
Agree.  No one has gotten around to it yet.  Also would be nice to have pause, rewind, single-step etc in a plan viewer display.

**Comment by mikeferguson** [comment]
+1 to breaking it out, and +1 to the single step ability, both would be quite useful

**Comment by davetcoleman** [comment]
Please see https://github.com/ros-planning/moveit_ros/pull/549

**Comment by mikeferguson** [comment]
#551
