### ISSUE TITLE
MoveIt Fails to Compile After Installing From Source

### ISSUE THREAD

**Issue by palanc** [moveit/moveit_ros#479]
Hello,

I have been trying to compile MoveIt from source, but whenever I try to compile, it fails at the end. The errors that I get are:

[ 89%] Built target moveit_motion_planning_rviz_plugin
[ 92%] Built target moveit_benchmark_gui
[100%] Built target moveit_setup_assistant_widgets
[100%] Built target moveit_setup_assistant
Linking CXX executable /home/planc509/catkin_ws/devel/lib/moveit_planners_ompl/moveit_demo_construct_constraints_database
CMakeFiles/moveit_demo_construct_constraints_database.dir/src/demo_construct_state_database.cpp.o: In function `computeDB(boost::shared_ptr<moveit::core::RobotModel> const&, unsigned int, unsigned int)':
demo_construct_state_database.cpp:(.text+0x82d): undefined reference to`planning_scene::PlanningScene::PlanningScene(boost::shared_ptrmoveit::core::RobotModel const&, boost::shared_ptr<collision_detection::World>)'
collect2: ld returned 1 exit status
make[2]: **\* [/home/planc509/catkin_ws/devel/lib/moveit_planners_ompl/moveit_demo_construct_constraints_database] Error 1
make[1]: **\* [moveit/src/moveit_planners/ompl/ompl_interface/CMakeFiles/moveit_demo_construct_constraints_database.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

It seems to be a linking error but I'm not sure how to fix it. I'm using ROS-Hydro on Ubuntu 12.04. Any help would be much appreciated, thanks!

**Comment by mikeferguson** [comment]
more than 6 months old, probably fixed by newer releases since there have been no additional reports
