### ISSUE TITLE
Planning scenes created with one robot cannot be loaded with other robots

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#48]
If I run the plugin for a robot and create a planning scene, I cannot import the scene geometry for another robot. I'm getting the following message, but no geometry appears:

Scene 'scene' was saved for robot 'my_robot' but we are using robot 'my_other_robot'. Using scene geometry only.

**Comment by marioprats** [comment]
Ok, I was pointed to #20 by @adamantivm and that worked!

**Comment by adamantivm** [comment]
How did you end up getting dynamic reconfigure gui to work on groovy?
- Julian

**Comment by marioprats** [comment]
I didn't :(
I finally set the parameter via rosparam

**Comment by adamantivm** [comment]
So perhaps we should open a ticket somewhere to record the fact that
dynamic reconfigure is not working in groovy, no?
Also, it would be probably good to modify the launch files we're using to
set this parameter by default
- Julian
