### ISSUE TITLE
moveit_pr2 move_group crashes with current hydro-devel setup

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_ros#481]
I´m using the following .rosinstall file, containing a current (mostly hydro-devel) MoveIt! setup: https://raw.githubusercontent.com/skohlbr/kohlbr_rosinstall/68932a86d004383b0c58bb18a1f2b50463132863/moveit_vigir.rosinstall

When installing this to a separate workspace, building and starting

<pre>
roslaunch pr2_moveit_config demo.launch debug:=true
</pre>

I get a segfault with the following backtrace in move_group:

<pre>
(gdb) bt
#0  0x00007ffff29f1d18 in bodies::ConvexMesh::useDimensions (this=0x14fcac0, 
    shape=0x1125220)
    at /home/kohlbrecher/tmp/moveit_vigir/src/moveit/geometric_shapes/src/bodies.cpp:776
#1  0x00007ffff29ede74 in bodies::Body::setDimensions (this=0x14fcac0, shape=
    0x1125220)
    at /home/kohlbrecher/tmp/moveit_vigir/src/moveit/geometric_shapes/src/bodies.cpp:110
#2  0x00007ffff2a19cc3 in bodies::ConvexMesh::ConvexMesh (this=0x14fcac0, 
    shape=0x1125220)
    at /home/kohlbrecher/tmp/moveit_vigir/src/moveit/geometric_shapes/include/geometric_shapes/bodies.h:404
#3  0x00007ffff2a19079 in bodies::createBodyFromShape (shape=0x1125220)
    at /home/kohlbrecher/tmp/moveit_vigir/src/moveit/geometric_shapes/src/body_operations.cpp:59
#4  0x00007fffca871154 in point_containment_filter::ShapeMask::addShape (this=
    0x1125320, shape=..., scale=1, padding=0.10000000000000001)
    at /home/kohlbrecher/tmp/moveit_vigir/src/moveit/moveit_ros/perception/point_containment_filter/src/shape_mask.cpp:70
#5  0x00007fffcab2066a in occupancy_map_monitor::PointCloudOctomapUpdater::excludeShape (this=0x14e9e30, shape=...)
---Type <return> to continue, or q <return> to quit---
</pre>

I´m on 12.04/64Bit/ROS Hydro. Any suggestions for getting rid of this segfault are appreciated.

**Comment by dornhege** [comment]
The above referenced commits should fix this.

**Comment by skohlbr** [comment]
Nice catch :) I'll merge into my indigo testing branch and report back.
