### ISSUE TITLE
Cannot load MotionPlanning display in RVIZ, asking for "liborocos-kdl.so.1.3"

### ISSUE THREAD

**Issue by MuhammadBadr** [moveit/moveit_ros#482]
Hi, I followed the installation instructions for ROS Hydro and MoveIt on Ubuntu 12.04, I'm following the tutorials and launched "pr2_moveit_config demo.launch". In RVIZ; I get a red circle next to the MotionPlaning display and the following error at the bottom;

MotionPlanning
The class required for this display, 'moveit_rviz_plugin/MotionPlanning', could not be loaded.
Error:
Failed to load library /opt/ros/hydro/lib/libmoveit_motion_planning_rviz_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = liborocos-kdl.so.1.3: cannot open shared object file: No such file or directory)

All I can find by googling is that it should be looking for liborocos-kdl.so.1.2 and not liborocos-kdl.so.1.3 for Hydro

**Comment by gavanderhoorn** [comment]
Also on ROS Answers: [Rviz motion_planning Error: Failed to load library](http://answers.ros.org/question/194341/rviz-motion_planning-error-failed-to-load-library/) (also multiple others).

Is this a buildfarm issue?

**Comment by mikeferguson** [comment]
Looks like liborocos-kdl 1.3 was released into hydro on July 17th (https://github.com/ros/rosdistro/commit/0ee099a33c4c841525493c802ea674a932293d16). The recommended "sudo apt-get update" and "sudo apt-get dist-upgrade" should fix this.
