### ISSUE TITLE
New Hydro Error Introduced for Kinematic Solvers

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#485]
@DLu brought up an issue on the mailing list [Upgrading MoveIt Versions 0.5.16->0.5.19 Breaks My Configuration](https://groups.google.com/forum/#!topic/moveit-users/tst9_1cmGfY) that called my attention to a recent change in how IK solvers initialize. 

With commit [robot_model_loader.cpp: added call to KinematicsBase::supportsGroup()](https://github.com/ros-planning/moveit_ros/commit/c2ee3bea81d694ee7414dc45f11b5f2809a4a803) there are now a number of new error messages appearing when MoveIt! is loaded, such as David's issue:

> [ERROR] [1406859674.089600466, 57.148000000]: Kinematics solver of type 'kdl_kinematics_plugin/KDLKinematicsPlugin' could not be initialized for group 'waist'
> [ERROR] [1406859674.090025890, 57.148000000]: Kinematics solver could not be instantiated for joint group waist.

The error is because previously users have added KDL or whatever IK solver they desired to their planning groups in the Setup Assistant, even when that planning group is not a chain.

To help fix this, I attempted to add a check in the Setup Assistant that prevents users from matching an incorrect IK solver to a planning group. I was unable to do this, however, because the interface to `KinematicsBase` is too ROS parameter server-centric and requires that the IK solvers are initialized by reading the SRDF and URDF from the parameter server. Its possible to work around that of course, but it started to look too messy for the flow it should be. I have lots of ideas for how to improve KinematicsBase, as I began to discuss in https://github.com/ros-planning/moveit_core/issues/161.

Overall, I'm opening this issue to possibly discuss several bigger issues that deserve their own thread:
- There are many users who might start experiencing IK errors with the latest debian release
  - Proposed solution: just email ROS-users mailing list telling people how to remove IK solvers for incorrect planning groups
- KinematicsBase is too legacy and needs to be updated for speed
  - Proposed solution: stop trying to support users who do not want to upgrade, or start on MoveIt! 2.0
- We broke stuff mid ROS Hydro release
  - Proposed solution: we should stop doing development on Hydro and just on Indigo or even now, on ROS-J

**Comment by DLu** [comment]
+1

**Comment by mikeferguson** [comment]
We have discussed versioning quite a bit... this ticket is no longer really actionable
