### ISSUE TITLE
depth_image_octomap_updater depends on moveit_occupancy_map_monitor (indigo-devel)

### ISSUE THREAD

**Issue by coolvision** [moveit/moveit_ros#494]
moveit_occupancy_map_monitor is not in target_link_libraries for depth_image_octomap_updater, in indigo-devel

compare:
https://github.com/ros-planning/moveit_ros/blob/indigo-devel/perception/depth_image_octomap_updater/CMakeLists.txt
https://github.com/ros-planning/moveit_ros/blob/hydro-devel/perception/depth_image_octomap_updater/CMakeLists.txt

because of that I was getting link errors: http://answers.ros.org/question/192962/osx-109-link-errors-for-depth_image_octomap_updater-indigo-devel-branch/

was it removed intentionally? should it be added there, same as in hydro-devel?

**Comment by davetcoleman** [comment]
That patch certainly should be in both branches, it has just been hard to keep them in sync. I've done my best to apply my PRs to both, but this one still needs to be done. Please submit a PR and I'll review / merge!

**Comment by mikeferguson** [comment]
This was fixed in #513
