### ISSUE TITLE
Announce joystick interface

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#496]
Follow-up from PR https://github.com/ros-planning/moveit_ros/pull/471

@garaemon 

Items remaining:
- [x] Fix formatting of documentation
- [x] Add documentation link to website
- [x] Release new debians of Hydro and Indigo
- [x] Announce on mailing list
## Fix formatting of documentation

I just checked and the tutorial page is now online but its format is off:
http://docs.ros.org/hydro/api/moveit_ros_visualization/html/doc/joystick.html

The original:
https://github.com/garaemon/moveit_ros/blob/3e48e5c94c351b80a4a9de0be74d06383f761ccb/visualization/doc/joystick.rst

How to do table formats:
http://sphinx-doc.org/rest.html
## Release new debians of Hydro and Indigo

@sachinchitta @hersh are there any specific plans for the next release? There have been a lot of changes since the last one.

**Comment by davetcoleman** [comment]
I've emailed Sachin about the moveit website.

**Comment by v4hn** [comment]
@davetcoleman can this be closed? I suppose after two years the "news" is rather outdated :-)

**Comment by davetcoleman** [comment]
i think you bring up a good point about the need to update the website - we need to add a simple one-line link to this tutorial but I believe only @sachinchitta has access to it. i think all the maintainers should get access

**Comment by sachinchitta** [comment]
The MoveIt! website was moved (long ago) to github-pages explicitly to allow people to contribute - you just have to do a PR against (https://github.com/julienking/julienking.github.io). The MoveIt! tutorials live within the code (https://github.com/ros-planning/moveit_pr2/tree/indigo-devel/pr2_moveit_tutorials) and have always been easy to contribute to just the way you contribute code.

**Comment by davetcoleman** [comment]
created PR
