### ISSUE TITLE
visualization/joystick_control/launch doesn't exist for installation

### ISSUE THREAD

**Issue by jasedit** [moveit/moveit_ros#500]
Whenever I attempt to install moveit_ros, I get the following error:

```
CMake Error at external/moveit/moveit_ros/visualization/cmake_install.cmake:67 (FILE):
  file INSTALL cannot find
  "/home/jpz/catkin_ws/src/external/moveit/moveit_ros/visualization/joystick_control/launch".
Call Stack (most recent call first):
  cmake_install.cmake:291 (INCLUDE)


make: *** [install] Error 1
Invoking "make" failed
```

visualization/CMakeLists.txt still references installing this file, which doesn't appear to exist anymore. Is it acceptable to issue a pull request to fix this issue? Or is there a particular process for resolving this?

**Comment by davetcoleman** [comment]
What version of ROS are you using?

**Comment by jasedit** [comment]
ROS Indigo on Ubuntu 14.04, 64-bit.

**Comment by davetcoleman** [comment]
> Is it acceptable to issue a pull request to fix this issue?

Always! This open source project needs as much help as possible :-)

But I think I fixed it for you, please check:
https://github.com/ros-planning/moveit_ros/pull/501

**Comment by jasedit** [comment]
Ach - had one ready to go. Thanks for the quick response!

**Comment by davetcoleman** [comment]
Sorry, just send a PR next time instead of an issue
