### ISSUE TITLE
planning_scene_monitor can crash when clearing Octomap due to mutex issue

### ISSUE THREAD

**Issue by jasedit** [moveit/moveit_ros#514]
If the clear Octomap interface is used, there's a thread safety issue which can result in a crash. According to gdb, the PlanningSceneMonitor is calling `clearOctomap()` in one thread, and the PlanningScene is calling `getPlanningSceneMsgOctomap()` in another. `clearOctomap()` is destructing OcTreeNodes, while `getPlanningSceneMsgOctomap()` is writing them. I can't figure out where to correctly lock/unlock the mutex for the octree, however.

**Comment by skuna** [comment]
Same issue as described in #291.

All calls to `PlanningScene::getPlanningSceneMsg()` and `PlanningScene::getPlanningSceneDiffMsg()` in `PlanningSceneMonitor::scenePublishingThread()` (in total these are three) should be surrounded by

```
if (octomap_monitor_) octomap_monitor_->getOcTreePtr()->lockRead();
```

and

```
if (octomap_monitor_) octomap_monitor_->getOcTreePtr()->unlockRead();
```

**Comment by jbohren** [comment]
Hey guys, check out this PR: https://github.com/ros-planning/moveit_ros/pull/554
