### ISSUE TITLE
export point_containment_filter as single executable or nodelet for perception usage

### ISSUE THREAD

**Issue by garaemon** [moveit/moveit_ros#516]
I'd like to use point_containment_filter outside of moveit, only for perception.
Is there any code already for such kind of purpose?

**Comment by garaemon** [comment]
[pr2_navigation_self_filter](https://github.com/PR2/pr2_navigation/tree/hydro-devel/pr2_navigation_self_filter) is a package for that purpose, 
however if we can use moveit codebase, it would be better.

**Comment by mikeferguson** [comment]
As far as I know, there is no nodelet/executable, however, the filter library + headers should be installed properly so that you could write such a nodelet/executable that links to the library (and depends on the moveit_ros_perception package).

**Comment by garaemon** [comment]
@mikeferguson I see, I will write them by using moveit as a library.
Thanks
