### ISSUE TITLE
Indigo devel job is failing

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#524]
Recently setup to run, but is failing. Even though debs are building, one of the tests does not build, details at:

http://jenkins.ros.org/job/devel-indigo-moveit_ros/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/1/console

**Comment by mikeferguson** [comment]
Now building, however, is unstable as freeglut cannot open a display on the farm.

**Comment by mikeferguson** [comment]
And we're in the green http://jenkins.ros.org/job/devel-indigo-moveit_ros/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/3/changes

**Comment by davetcoleman** [comment]
Thanks for all the fixes!
