### ISSUE TITLE
install moveit on Ubuntu 14.04 with ROS indigo

### ISSUE THREAD

**Issue by sherry0009** [moveit/moveit_ros#527]
Hi, I am trying to install moveit on Ubuntu 14.04 with ROS indigo. I followed the installation instructions (http://moveit.ros.org/wiki/Installation) and changed "hydro" to "indigo". Then,  the following error appears：
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pr2_moveit_plugins: Cannot locate rosdep definition for [pr2_controllers_msgs]
pr2_moveit_config: Cannot locate rosdep definition for [pr2_description]

Please tell me how can I resolve it.

Regards.

**Comment by mikeferguson** [comment]
Looks like nothing pr2-related has been released into Indigo except pr2_mechanism_msgs. I would suggest removing the "moveit_pr2" line from the rosinstall file as it's really not needed (unless you want to plan for PR2, in which case you will probably have to build all of that PR2 stuff from source)

**Comment by sherry0009** [comment]
It works.Thank you so much!
