### ISSUE TITLE
Support for alternate collision checkers?

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_ros#532]
I've now written my own collision checker, complete with derived CollisionWorld/CollisionRobot -- but it seems there is no elegant way to load these? My first (hacky) approach was to write a move_group_capability that simply called setActiveCollisionDetector on the planning scene. This managed to get my custom code loaded through the move_group_capability plugin loader and active -- however, it means that the RVIZ plugin is still not using my collision checker with IK.

My current thought is that we need to:
- Define a plugin API for adding collision detectors.
- Define an optional ROS parameter that holds the name of a desired collision detector to load, and then  have the PlanningSceneMonitor load it, and make it active.

@isucan Does this sound about right? Is there a better approach? The code for the RVIZ plugin jumps around a bunch -- but I presume at the core it still uses the PlanningSceneMonitor, and so this approach would get me the desired results in RVIZ?

**Comment by isucan** [comment]
Hey Mike,

In short, you are right, your plan is the right way to go.
At some point we wanted to have a plugin interface for collision checkers, but we never got to it. I was thinking that with collision detection algorithms, we could probbaly figure out which one is the better one and we could kind of hard code the better one. However, that may not be the case.

**Comment by mikeferguson** [comment]
Thanks for responding. I will whip up a first pass and open a PR for discussion.

**Comment by mikeferguson** [comment]
This is now merged.
