### ISSUE TITLE
[perception] padding scale parameters inverted for collision objects

### ISSUE THREAD

**Issue by romayiii** [moveit/moveit_ros#537]
Hi,
    working with the padding parameters to clear the octomap (as described in #315) I found that the parameter "padding_scale" is working properly for the robot model, but is inverted for the collision objects in the scene.

Testing with padding_scale: 1.0

![paddig_1 0](https://cloud.githubusercontent.com/assets/8075064/5231828/62ee9238-7740-11e4-9813-765ede11cfbf.png)

The collision object (green long board over the table) is perfectly cleared out from the octomap, however, when:

Testing with padding_scale: 1.5

![padding_1 5](https://cloud.githubusercontent.com/assets/8075064/5231840/96d8ffe8-7740-11e4-9dc8-f55c222861c5.png)

The collision object is not complete cleared from the octomap. One can see how with with padding_scale: 1.5 the robot's "belly" is being cleared out from the octomap (table) because of the increase in the padding_scale as expected, but I was expecting that the octomap near the collision object would also be cleared in a bigger section, but it happens exactly the opposite.

Ubuntu 14.04, with Indigo, moveit_core and moveit_ros installed from source, other moveit packages are the lates .deb 

My yaml flie for sensor parameters:

<pre>
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /scan_cloud
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.0
    padding_scale: 1.5
    filtered_cloud_topic: filtered_cloud
</pre>

Thanks

**Comment by skohlbr** [comment]
This is fixed by this pull request: https://github.com/ros-planning/geometric_shapes/pull/25

**Comment by mikeferguson** [comment]
@skohlbr noted that this is fixed by https://github.com/ros-planning/geometric_shapes/pull/25, which is also https://github.com/ros-planning/geometric_shapes/pull/34 in indigo
