### ISSUE TITLE
implement functionality that corresponds to TrajectoryConstrains

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#55]

**Comment by mateiciocarlie** [comment]
Can you please expand on this a bit? I was also thinking about trajectory constraints as a next step in the benchmarking context, so I was wondering if this is related.

**Comment by isucan** [comment]
hey Matei. Sorry -- i put this here mostly as a reminder for me. Everything in MoveIt is with respect to constraints.
So you have:
1. goal constraints (obvious I guess) -- they just specify regions to be accepted as goals
2. path constraints -- they define constraints to be enforced for every state along a path. This should work already, and we have run benchmarking for this too in the past. I have not hand a chance to try it recently and a number of things have changed, so minor issues may need to be resolved.
3. trajectory constraints -- for lack of a better name. These are essentially sequences of constraints that need to be met by a particular motion plan. So for instance, if I'd like a robot's end effector to follow a particular path (e.g. pull the gripper back, in a straight line), I can pass to the planner a sequence of position + orientation constraints for the end effector. Then the planner will satisfy those constraints, in order, and it will plan for the remaining DOF.  This does not have to be limited to the redundancy  -- if we have a sampler for a different group, we can use the base. 

The part in 3 is not complete yet, but should be soon. I also plan to port a sampler for robot states that includes base sampling, but this will be a bit more work and probably in a different ticket.

**Comment by isucan** [comment]
initial version checked in
