### ISSUE TITLE
Updated binary not available at Ubuntu Package: Debian Installation

### ISSUE THREAD

**Issue by adnanmunawar** [moveit/moveit_ros#550]
While this is not an issue per se with the code in this repo, however, I believe that the latest build from the current source code is not available as Deb Installations (at least for Hydro-devel). The reason I am saying that is that the following issue :https://github.com/ros-planning/moveit_ros/commit/1f4f175ff65a80479ad143fdf1799fe185be5823#diff-2c9d4c73e97bad89591e5b93c3080ed7

still haunts benchmarking while MoveIt is installed from Ubuntu Debs (this issue: https://groups.google.com/forum/#!msg/moveit-users/DjI9yE_BoHU/oa9IvVrUTmoJ), while I just removed that and compiled from source and the issue is not longer there. Please look into it.

**Comment by mikeferguson** [comment]
This is included in 0.5.20 -- which has been released on 12/10, but is still only in shadow-fixed -- should end up in the next Hydro sync to public (which I imagine will land any day now). See http://www.ros.org/debbuild/hydro.html for details.
