### ISSUE TITLE
benchmark tool does not find planners

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#56]
I'm getting the following error on the benchmark server side:

The planner id 'BKPIECEkConfigDefault' is not known to the planning interface 'ompl_interface_ros/OMPLPlanner'
Planning interface 'ompl_interface_ros/OMPLPlanner' has no planners defined

The client side shows:

[ INFO] [1354662258.176541272]: Calling benchmark for goal constraints 'shelf table tight 1_pose_0000' for scene 'shelf table tight 1' ...
[ERROR] [1354662258.253907686]: Exception thrown while while deserializing service call: Buffer Overrun

Tried with different planners
Thx!

**Comment by adamantivm** [comment]
Mario, did you check in ~/.ros to see if the benchmark produced results
anyway? That was the case for me.
- Julian

**Comment by isucan** [comment]
This was due to the group name not being specified. Perhaps a better error message should appear as well.

**Comment by davetcoleman** [comment]
I've fixed the bad error message issue when you forget to assign a group: https://github.com/davetcoleman/moveit_ros/commit/e1e01d14dd34e25f91411a099a43db9695f5728e

However I'm still getting "Exception thrown while deserializing service call" even though the benchmark server works fine.

**Comment by davetcoleman** [comment]
I looked into this further and the service response being sent back is 141 KB - that really isn't very big. Should we consider putting this bug on the [roscpp](https://github.com/ros/roscpp_core) issue list?

**Comment by mikeferguson** [comment]
Benchmarks to be replaced under https://github.com/ros-planning/moveit/issues/25
