### ISSUE TITLE
Adding a rviz motion planning plugin causes RViz to hang and die [Solved] [If TF isn't being published, causes crash]

### ISSUE THREAD

**Issue by UltronDestroyer** [moveit/moveit_ros#566]
Is there anything I need to provide? This does not work with a robot generated via MoveIt!

**Comment by mikeferguson** [comment]
Are you sure all your rviz and plugin debs are up to date? If they weren't all built at the same time you might be hitting an ABI compatibility problem. I've not currently been having any problems with the motion planning plugin.

**Comment by UltronDestroyer** [comment]
I did run a dist-upgrade and update beforehand.

**Comment by UltronDestroyer** [comment]
Perhaps I should add shadow-fixed to my install list?

**Comment by UltronDestroyer** [comment]
Sorry Mike, this was my erro. I had set Gazebo physics to "False" which caused TF not tobe published. When TF isn't published, the motion planning plugin causes RViz to hang and die.

**Comment by mikeferguson** [comment]
That sounds like a possible problem -- please update the description of the ticket to be about lack of TF causing a crash (I can believe that)

**Comment by UltronDestroyer** [comment]
Ok, I've updated the title of the ticket and renamed it to solved (with a tl;dr). I'm going to close it now.

**Comment by davetcoleman** [comment]
Its not clear this was solved - is there not a bug with the motion planning plugin when no tf is published? This could be fixed with an error message to help future users.
