### ISSUE TITLE
Rviz Plugin "Set Start to Current" sets start to "Home" position

### ISSUE THREAD

**Issue by sksellio** [moveit/moveit_ros#57]
The "Set Start to Current" button in the rviz plugin sets the start to be the "home" position with the arm by the robot's side. "Set Goal to Current" does the same. The robot model is updating and tracking the arm but the plugin isn't taking into account the current state.

**Comment by isucan** [comment]
This is actually what the code is supposed to do. There was a bug earlier that took the robot state directly. To obtain the behaviour you want you should enable the scene update event for the planning_scene_monitor publishing updates, thus having the current scene state follow the state of the robot itself.
