### ISSUE TITLE
benchmarks missing tf dependency

### ISSUE THREAD

**Issue by mryellow** [moveit/moveit_ros#572]
It appears `moveit_ros_benchmarks` is missing a dependency for `tf`.

My environment is a little out of the ordinary which might be why this hasn't come up earlier, debian jessie with mostly source installs in a parent catkin workspace, jessie has few pre-compiled packages.

Was getting not found errors on `tf/tf.h` compiling `moveit_ros_benchmarks`, patching it's `package.xml` and `CMakeLists.txt` to include `tf` worked.

**Comment by davetcoleman** [comment]
Perhaps some change elsewhere revealed this discrepancy. It can't hurt to add it either way - could you put in a PR?

**Comment by mryellow** [comment]
Will do, gotta get some "work work" done, will hit it this-afternoon sometime.
