### ISSUE TITLE
[indigo] Destroys command line arguments

### ISSUE THREAD

**Issue by atenpas** [moveit/moveit_ros#598]
The indigo version destroys command line arguments. Command line arguments are destroyed when passed to roscpp_initializer.

I had to manually change the following line in /opt/ros/hydro/lib/python2.7/dist-packages/moveit_commander/roscpp_initializer.py:

```
args2 += a
```

to this:

```
args2.append(a)
```

Without this change, for example, topic remapping fails.

**Comment by dornhege** [comment]
Should this maybe go to moveit_commander?

This should be fixed in ros-planning/moveit_commander@147e0f0e.
