### ISSUE TITLE
Better approximation of a Jinv controller in the Kinematics Tool

### ISSUE THREAD

**Issue by mateiciocarlie** [moveit/moveit_ros#6]
The KDL IK based behavior is a good substitute for seeing what a Jinv or Jt controller would do, as long as you're in the reachable workspace. Once you move out, it is unresponsive and hard to use. I (think I) understand why it's doing that: it queues up all the poses you go through, tries IK for all of them and fails, and the queue must clear up before it regains responsiveness. 

A real controller though would behave differently - it would just constantly try to move in a straight line (in the direction of the gradient) towards the current goal, and just push against a joint limit if it can not get there. It never looses responsiveness trying to go to where the goal used to be. Can we get similar behavior out of the KDL IK based version? Sorry if this is unclear, would be happy to chat more in person.

**Comment by marioprats** [comment]
There is now a "Cartesian teleop" checkbox. When checked, velocity IK is called instead of the default position one, thus working similar to a cartesian controller. Please reopen if you see any issues.
