### ISSUE TITLE
Additional Metrics for Benchmarking

### ISSUE THREAD

**Issue by amdshameer** [moveit/moveit_ros#600]
I would like to add few more criteria(i.e additional metrics) for benchmarking **other than** number of  runs like below:
- solution(path) length
- graph states(no. of samples generated)

Also I would like to give value to the parameter of planners in the config file itself as it is here http://ompl.kavrakilab.org/benchmark.html Let's say I want to add RRTConnectkConfigDefault.range=100. 
How should I do it? Please kindly help me in it
@isucan @davetcoleman @sachinchitta

**Comment by mikeferguson** [comment]
https://github.com/ros-planning/moveit/issues/25
