### ISSUE TITLE
Install Error: ompl-config.cmake

### ISSUE THREAD

**Issue by rizasif** [moveit/moveit_ros#601]
Hello, I am following the installation guide on: http://moveit.ros.org/install/

While doing catkin_make the following error comes up:

---

CMake Error at moveit_planners/ompl/CMakeLists.txt:20 (find_package):
  By not providing "FindOMPL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OMPL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OMPL" with any of
  the following names:

```
OMPLConfig.cmake
ompl-config.cmake
```

  Add the installation prefix of "OMPL" to CMAKE_PREFIX_PATH or set
  "OMPL_DIR" to a directory containing one of the above files.  If "OMPL"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/rizasif92/Documents/Software/moveit/build/CMakeFiles/CMakeOutput.log".
See also "/home/rizasif92/Documents/Software/moveit/build/CMakeFiles/CMakeError.log".

---

I have tried everything to install ompl-config.cmake files but everything was useless.
Please help me

**Comment by v4hn** [comment]
You simply did not have http://ompl.kavrakilab.org installed on your system where cmake can find it.
Without the Motion Planning Library you can't build MoveIt!'s wrapper for it.
Closing this issue as invalid/non-fixable.
