### ISSUE TITLE
Inconsistent moveit_ros and moveit_msgs with Indigo?

### ISSUE THREAD

**Issue by RashmicaG** [moveit/moveit_ros#615]
The file moveit_ros/warehouse/warehouse/src/warehouse_services.cpp trys to include " moveit_msgs/SaveRobotStateToWarehouse.h" but I cannot find this in moveit_msgs/msg/

-- This is consistent with the latest versions on Git for Indigo. Does anyone know how to resolve this?

**Comment by davetcoleman** [comment]
Seems related to https://github.com/ros-planning/warehouse_ros/pull/22

**Comment by sachinchitta** [comment]
No, it was related to this: https://github.com/ros-planning/moveit_msgs/pull/14

**Comment by sachinchitta** [comment]
Fixed.
