### ISSUE TITLE
MoveIt with source installed OMPL

### ISSUE THREAD

**Issue by amdshameer** [moveit/moveit_ros#623]
I have a source installation of OMPL. How do I set MoveIt! to use the source installation of ompl? It works only when I do "sudo apt-get install ros-hydro-ompl". It does not find OMPL, If I remove "ros-hydro-ompl".
@davetcoleman @isucan @sachinchitta 

Actually I _WAS_ able to use source built MoveIt with source built OMPL. I was able to modify planner parameters and did the planner optimization for my project. I did not use catkin_make_isolated to build them.

Things I did:
1) Installed MoveIt from source. While installing MoveIt, it will install ros-hydro-ompl. So I had to do "sudo apt-get remove ros-hydro-ompl" to remove ompl.

MoveIt path in my ubuntu was: /home/shameer/moveit
Installation Link:http://moveit.ros.org/install/

2) Installed OMPL from source

OMPL path in my ubuntu was: /home/shameer/ompl
Installation Link:http://ompl.kavrakilab.org/core/installation.html
I followed the same link to compile them

Now:
I did those three steps in my new laptop. But I am not able to use source built OMPL with MoveIt(source built too) . If I can recollect what I did in the third step, would help me to use source built OMPL with MoveIt(source built).
Could you please shed some lights on it?

**Comment by amdshameer** [comment]
I solved it. You don't need catkin_make_isolated. I followed http://ompl.kavrakilab.org/buildSystem.html Just follow the steps below:

1st step:
Install MoveIt from source
After successful installation of MoveIt from source, do "sudo apt-get remove ros-hydro-ompl" and "sudo apt-get purge ros-hydro-ompl"
path: /home/name/moveit

2nd step:
git clone https://github.com/ompl/ompl.git
path: /home/name/ompl
cd ompl/
mkdir -p build/Release
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
make install
sudo make install
cd Release/
cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
cd ..
make -j 4 update_bindings
make 
sudo make install

So this made me use source built OMPL with my youBot moveit package(catkin package).
Also DON'T FORGET TO export CMAKE_PREFIX_PATH="/home/name/project_ws/devel:/opt/ros/hydro:/home/name/moveit/devel"

@isucan @davetcoleman @sachinchitta

**Comment by liuyouzhao** [comment]
What you tried are very helpful to me, thanks very much.

**Comment by davetcoleman** [comment]
See also: http://moveit.ros.org/install/source/dependencies/
