### ISSUE TITLE
Benchmark tool IK solver failed with error -6

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#66]
I create a scene and a constraint with the moveit plugin. Inside the plugin double-clicking the constraint computes the IK and a solution is found, so the goal is reachable. However, when running the benchmark tool on this scene I get this error:

[ WARN] [1354844470.079475944]: It looks like the planning volume was not specified.
[ INFO] [1354844470.086848920]: Planner configuration 'arm[BKPIECEkConfigDefault]' will use planner 'geometric::BKPIECE'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1354844470.088222357]: Attempting to use default projection.
[ INFO] [1354844470.106765389]: Starting with 1 states
[ERROR] [1354844470.596659101]: IK solver failed with error -6
[ERROR] [1354844471.102957452]: IK solver failed with error -6
[ERROR] [1354844471.603711269]: IK solver failed with error -6
[ERROR] [1354844472.097742587]: Unable to sample any valid states for goal tree
[ INFO] [1354844472.097790450]: Created 1 (1 start + 0 goal) states in 1 cells (1 start (1 on boundary) + 0 goal (0 on boundary))
[ INFO] [1354844472.097817136]: No solution found after 2.009304 seconds
[ERROR] [1354844472.109146345]: IK solver failed with error -6
[ INFO] [1354844472.109397973]: Unable to solve the planning problem

**Comment by marioprats** [comment]
Some more info: looking into the error codes, -6 corresponds to a timeout, and going into the code (moveit_core/constraint_samplers/src/default_constraint_samplers.cpp:225), the timeout is hardcoded to 0.5. Could that have something to do?

**Comment by isucan** [comment]
I added the option as a parameter that can be specified in the kinematics.yaml file. The pr2 default config has this parameter now specified, and set to 0.5; The setup assistant allows specifying the param. Let me know if this is still a problem. Technically though, an IK timeout is not a big problem, so I will make that a debug message only.

**Comment by mateiciocarlie** [comment]
So wait - IK timeout is not a problem at all, it's just the IK tool's way of telling us that, as far as it's concerned, there is no solution, right?

**Comment by sachinchitta** [comment]
Does depend on the IK solver - but technically it really does mean that IK solver did not find the solution in the given time. May not mean that the solution does not exist.
