### ISSUE TITLE
Question (closed kinematic chains)

### ISSUE THREAD

**Issue by shisha101** [moveit/moveit_ros#661]
We have a delta robot and would like to use move it to check for collision avoidance and planning, currently we can plan simple trajectories without collision checking. would MoveIt be able to carry out collision checking and planning if a special IK plugin was written for the robot ? or is there something we might be missing here?

From what we understand is that using URDFs it is not possible to model chains, only trees are possible, so we are using our own fwd/inv kinematics algorithms to publish the TFs and joint states, this is currently working well.

**Comment by davetcoleman** [comment]
Yes, the default IK, KDL, only handles chains so you would need to create your own IK solver. It would be really cool if you could share this closed kinematic chain IK solver especially if its robot agnostic

URDFs can model _open chains_ but not _closed chains_ (except for a hacky mimic joint that is partially supported)
