### ISSUE TITLE
Travis for Ubuntu Trusty

### ISSUE THREAD

**Issue by 130s** [moveit/moveit_ros#665]
Could any admins enable Travis at https://travis-ci.org/profile/ros-planning/ (can be done with a single click) and poke me? Thanks in advance.

(I assume the reason why Travis is disabled is the same as ros-planning/moveit_commander#44 (comment)).

**Comment by davetcoleman** [comment]
ive gone ahead and turned on travis for all the primary moveit repos, perhaps you could update the .travis file for all of them? thanks for your effort on this!
