### ISSUE TITLE
To compile moveit_ros, I needed indigo-devel of moveit_core, jade-devel of moveit_ros, and jade-devel of moveit_msgs

### ISSUE THREAD

**Issue by UltronDestroyer** [moveit/moveit_ros#670]
Is this intended? Any other configuration gave me grief, even with using the most recent deb packages.

**Comment by rhaschke** [comment]
The new Travis CI test succeed, both on [jade](https://travis-ci.org/ros-planning/moveit_ros/builds/130391051) and [indigo](https://travis-ci.org/ros-planning/moveit_ros/builds/130391657).
Can you provide more details, please?

**Comment by v4hn** [comment]
This is not the case (anymore?). Closing as resolved.
