### ISSUE TITLE
Schunk LWA4P joint 5 angle’s origin changes on Robot On/OFF

### ISSUE THREAD

**Issue by SaranKanag** [moveit/moveit_ros#672]
I tried a pick and place application developed in ROS with Schunk LWA4P robotic arm. Initially it worked fine completely. Even when I shut down the robot at positions apart from home (all angles 0 degree) it worked fine on next new initialization. 
But now I am facing a weird problem with joint 5’s angle. For example when I shut down my robot with a pose which has following angles values, (as obtained from rostopic “/arm/joint_states”)

> _Joint 1 = 1.57 radians; Joint 2 = -1.23 radians; Joint 3 = 1.88 radians; Joint 4 = 0.0 radians; **Joint 5 = 0.745 radians**; Joint 6 = -1.48 radians_

After ros service call for shut down, I turned off the robot and started again with new initialization. After initialization,rostopic “/arm/joint_states“ displays the angle values of same pose at which it stopped now as 

> _Joint 1 = 1.57 radians; Joint 2 = -1.23 radians; Joint 3 = 1.88 radians; Joint 4 = 0.0 radians; **Joint 5 = 0.0 radians**; Joint 6 = -1.48 radians_

I could see an incorrect joint 5 angle. 
Initially it was not happening but now it happens all the time when I newly start the robot. This mismatch occurs only at joint 5. 
Can anyone help me out in resolving the same?

**Comment by mikeferguson** [comment]
I'm pretty sure that this is an issue with your robot drivers -- not MoveIt -- as the joint_states should be coming from the drivers when you are running against the real hardware.

This ticket should be opened against the appropriate driver repository -- or perhaps the question should be asked on answers.ros.org, although that definitely sounds more like a bug than a user issue.
