### ISSUE TITLE
indigo/jade releases

### ISSUE THREAD

**Issue by v4hn** [moveit/moveit_ros#689]
- [ ] https://github.com/ros-planning/moveit_ros/pull/728 is a jade blocker (added 7/26/2016)

---

given that we have accumulated a number of bug fixes and the new ApplyPlanningScene service,
it would be great to have a new release of moveit_core and moveit_ros.

Are there any particular requests/issues we should wait for?

**Comment by 130s** [comment]
Something that may be nice to discuss; One thing we could do for the long existing PRs is to manually rebase them and at least have them go through CI tests.
Even we decided to do so, I'm still not sure if now is the right timing for doing so since it'll require resource (reviewers, time).

**Comment by davetcoleman** [comment]
+1 to releasing

The long existing PRs seem unrelated to the decision to release or not, no?

**Comment by 130s** [comment]
Well, one way to think is to process as many PRs as possible before the release.

But I guess we can also make smaller releases with more frequency, if that's what we're aiming. Then +1 for releasing.

**Comment by v4hn** [comment]
On Thu, Jun 16, 2016 at 10:11:24PM -0700, Isaac I.Y. Saito wrote:

> But I guess we can also make smaller releases with more frequency,
> if that's what we're aiming.

I suppose we should, if we want to have "regular" users use the deps
instead of their own source builds.

+1 that makes three of us.

**Comment by davetcoleman** [comment]
I never thought of it that way!

**Comment by 130s** [comment]
- Indigo 0.7.2 is out https://github.com/ros/rosdistro/pull/11899.
- For Jade (and presumably Kinetic), at least <s>https://github.com/ros-planning/moveit_ros/pull/607 needs resolved afaik.</s> https://github.com/ros-planning/moveit_ros/pull/699 needs merged.

**Comment by davetcoleman** [comment]
@130s Can we consider Jade "released" yet? Should we add installation instructions to the website?

Can we close this issue? Kinetic discussions are in other issues.

**Comment by davetcoleman** [comment]
jade discussion moved to https://github.com/ros-planning/moveit/issues/22
