### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#695]
I'm working on getting the [experimental merged repo for Kinetic](https://github.com/davetcoleman/moveit) to compile and I'm noticing a lot of missing dependencies. I'm opening this issue to provide a place to track those dependency issues.
- [ ] https://github.com/flexible-collision-library/fcl/issues/137
- [x] https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/7
- [x] https://github.com/ros-interactive-manipulation/household_objects_database_msgs/issues/3
- [ ] Cleanup extra [rosinstall instructions](https://github.com/ros-planning/moveit_docs/blob/kinetic-devel/moveit.rosinstall)
- [x] https://github.com/ros-planning/geometric_shapes/issues/47
- [x] https://github.com/ros-planning/moveit_core/issues/316
- [x] https://github.com/ros-planning/moveit_ros/issues/726
- [x] https://github.com/ros-planning/moveit_plugins/pull/22
- [x] https://github.com/ros-planning/moveit_setup_assistant/pull/120

**Comment by davetcoleman** [comment]
FCL blocker: https://github.com/ros-planning/moveit_core/issues/299

**Comment by davetcoleman** [comment]
@tfoote how do we go about getting "abandoned" ROS message repos released? Is anyone maintaining https://github.com/ros-interactive-manipulation/ ?

We need the follow two message package released:
https://github.com/ros-interactive-manipulation/
https://github.com/ros-interactive-manipulation/household_objects_database_msgs

**Comment by tfoote** [comment]
@davetcoleman Please open a ticket on the repos you need released. 

@jkammerl Could you add me to the ros-interactive-manipulation organization. You're the only publicly listed member. [Our policy](http://wiki.ros.org/RecommendedRepositoryUsage/CommonGitHubOrganizations#Guidelines_for_administering_ros-.2A_organizations_on_GitHub) is that the ROS platform manager is an owner on all `ros-*` repos to support maintainer handoffs.

**Comment by davetcoleman** [comment]
I have opened tickets there, see first two issues referenced inside this issue

**Comment by davetcoleman** [comment]
Also I believe @isucan is a member of ros-interactive-manipulation

**Comment by davetcoleman** [comment]
Required to build from source: https://github.com/ros-planning/moveit_ros/pull/698

**Comment by davetcoleman** [comment]
Moved ownership of ros-interactive-manipulation conversation to https://github.com/ros-interactive-manipulation/tabletop_object_perception/issues/3

**Comment by davetcoleman** [comment]
MoveIt! Kinetic is now passing on Travis, though requires these two PRs: https://github.com/ros-planning/moveit_core/pull/304, https://github.com/ros-planning/moveit_ros/pull/699.

Travis also passes for unified MoveIt! repo: https://github.com/davetcoleman/moveit

**Comment by dbolkensteyn** [comment]
Can anyone else reproduce this issue? If so it'd be a blocker IMO. https://github.com/ros-planning/moveit_setup_assistant/issues/119

**Comment by davetcoleman** [comment]
Moving this issue to new repo: https://github.com/ros-planning/moveit/issues/18
