### ISSUE TITLE
Add visual indicator of z-axis rotation to goal poses

### ISSUE THREAD

**Issue by adamantivm** [moveit/moveit_ros#70]
Otherwise it is really hard to tell the rotation of a  goal pose marker. This is particularly important for the case where we want multiple goal poses which are in the same location and only differ in the z-axis (e.g.: to different successful poses for grasping an object, only rotated 180°)

**Comment by mateiciocarlie** [comment]
There was a suggestion for the goal marker to actually use the geometry of the current end-effector. That would be ideal, but might be difficult?

On the way, a simple t-shaped marker will indeed be preferable to the current arrow.

**Comment by adamantivm** [comment]
I was suggesting to Mario simply to add a single tail fin to the arrow. I
think that would do for now, until we have the gripper mesh in place. What
do you think?

**Comment by marioprats** [comment]
For sure a T-shape arrow will be simpler. I'd for that now

**Comment by mateiciocarlie** [comment]
Yes, that would be good for now, and definitely an improvement over just-the-arrow.

Even like that though, it will be hard to know exactly where the gripper would go (is the base of the arrow where the palm would go? is the tip of the arrow where the fingers go? etc.) That might lead us to create goal poses where the gripper is colliding with stuff, and then we'll unfairly blame the planner or the kinematics.

As a matter of fact, the benchmark (or the plugin) should be able to check if a disembodied gripper at the goal pose is in collision with something, and then tell us the goal is invalid, and disregard it for statistics.

**Comment by adamantivm** [comment]
> As a matter of fact, the benchmark (or the plugin) should be able to
> check if a disembodied gripper at the goal pose is in collision with
> something, and then tell us the goal is invalid, and disregard it for
> statistics.

Maybe something easy to do would be to be able to run IK without collision
constrains. The same thing  you can do with double-clicking the goal but
removing the collision constrain, I mean. That way you can visually see if
there is a problem. Although I agree the general solution of drawing the
gripper is the ideal.

If you use a T-shape instead of an arrow, please make sure it is possible
to distinguish and click on two different goals which only differ in 180°
z-axis rotation

**Comment by sachinchitta** [comment]
Might be best to duplicate the axes display for each pose for now? - http://www.ros.org/wiki/rviz/DisplayTypes/Axes

**Comment by marioprats** [comment]
I have submited a pull request that provides L-shaped arrows. That will help for the moment. I've talked with Ioan and it does not seem too difficult to show the actual hand. So that will be the next.

**Comment by marioprats** [comment]
Solved from 99d80764f1fcd55a43ed38bf99e5488274545dfb and 20a8936aa464afc865c31bba98ab3f21069840cb
