### ISSUE TITLE
Eliminate from benchmark result goal poses where the gripper is in collision

### ISSUE THREAD

**Issue by mateiciocarlie** [moveit/moveit_ros#71]
If the gripper itself is in collision with something, then no collision-aware IK will ever find a solution regardless of the arm. Goal poses that put a particular gripper in collision with something should not be considered for the benchmark.

**Comment by isucan** [comment]
I think a more general approach is to use the benchmark results to filter this data out for the particular purpose of the experiment we are thinking about. The benchmarking infrastructure collects sufficient data to allow filtering the type of data you need.
