### ISSUE TITLE
IK computation of goal poses

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#76]
The IK computation for goal poses should be done as a background job so the UI does not hang.

**Comment by adamantivm** [comment]
I agree. Furthermore, it would be good to have a mechanism throughout the
plug-in to display progress of background operations.
Another example of this is loading scenes and goal poses from a database
through the network, it can take several minutes, throughout which there is
no feedback of what is going on.

**Comment by marioprats** [comment]
What is the approach for a BackgroundJob to access the ui?

**Comment by mateiciocarlie** [comment]
Would be nice for all computation to be done in the background, including for example the IK when dragging the start state robot or goal state robot around...

**Comment by isucan** [comment]
Most computation the plugin supports is done in background. The only operations that are not in background are ones that require rendering or user interaction (and of course, the bit mentioned in this issue :) )

@marioprats you just call addBackgroundJob() and pass it a boost function pointer. The same calling mechanism as addMainLoopJob(), except done in a different thread. addMainLoopJob() should be used for rendering / UI update operations. A background job can call addMainLoopJob() to access the UI.

**Comment by marioprats** [comment]
The IK computation on the goal pose, as it is now, displays an error message if a solution does not exist, so we cannot do it in a BackgroundJob unless we remove the feedback message, right? In general I would like to have feedback... what about replacing the error message by switching the marker color to red?
_Update_ - just read your last sentence ;) (A background job can call addMainLoopJob() to access the UI). So we can keep the current functionality

**Comment by mateiciocarlie** [comment]
Switching color to red instead of the "forbidden" marker would be great.

For example, in the "Gripper Click" interactive grasping strategy, there is no computation done in the rendering thread, but the gripper marker turns green if a solution has been found in the background, red if there is no solution, and grey if the background thread has not finished computation yet. The UI is always responsive.

**Comment by isucan** [comment]
@mateiciocarlie Trying to restate this: we should add a marker instead of the current sign (probably the end effector) and that should be red when there is a problem. This sounds like a nice feature.

When the solution works, I would like to keep things as they are, so the arm config is visible.

**Comment by mateiciocarlie** [comment]
Oh, sure - the arm config would always be visible. It's just that the computation itself should be done in a different thread so the UI is responsive. Right now, if you wander outside the reachable range, it becomes sluggish and difficult to work with. We just need a way to convey to the user three things: solution found, solution not found, and "working".

**Comment by isucan** [comment]
Sounds great! We keep finding really nice stuff to add :)

**Comment by marioprats** [comment]
Fixed in d5eda4c04e2c6fefa6aca74109e8d06ebc84402b
