### ISSUE TITLE
split motion_planning_frame.cpp into multiple files

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#77]

**Comment by isucan** [comment]
we need to do this relatively soon. Files are getting very large and we seem to keep on finding new things to add. 
For motion_planing_frame.cpp
Keep the the file as a master file for the frame + add new files, one for each tab;
@marioprats feel up to this?

motion_planning_display.cpp
-- separate out trajectory visualization as a first step.

**Comment by marioprats** [comment]
All right, I can try ;)

**Comment by marioprats** [comment]
Done in 94e5a172513220da47f3df506ec266f5303a88f1
