### ISSUE TITLE
benchmarking with invalid goal poses

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_ros#78]
Running motion planning benchmarks for goal poses that have no IK solution is not really meaningful for planning -- we would be basically testing reachability of the arm with hand selected goals.

We should add a button to the rviz pluing that allows starting a background job that computes IK for all defined goal poses. If IK was not yet run we use a default color for the marker. If it was, we use a color to mark failure and one to mark success. I believe @mateiciocarlie  suggested colors like gray, red, green for these cases. Then a 'select invalid' button might be helpful to change / delete poses.

Potentially interested people (feel free to add others):
@sachinchitta @marioprats @adamantivm

**Comment by marioprats** [comment]
I think it would be nice to have this functionality, specially for the case we want to benchmark planners. But in the case we just want to compare arm kinematics, and not planners, it may have sense not all the goals are reachable. The benchmark would give you how many goals are reachable with each arm, and then some metrics for the reachable ones.

**Comment by mateiciocarlie** [comment]
Agreed. We are essentially benchmarking three things, from a reachability perspective: the hardware itself, the IK, and the planner. Poses that are not reachable are very meaningful for the system, just not for the planning component.

What is nice, and I think is captured in a different ticket, is to remove goals that are invalid because the gripper would be in collision with something.

**Comment by isucan** [comment]
@mateiciocarlie agreed. I just think that in addition to the gripper being in collision we can actually test for IK solution existance as well, and in fact, complete collision checking would be possible then as well. Is there a reason not to test these?

I think it would be interesting to know if the planner failed because of an IK failure or because of the kinematics possible. What i mean is, it could be the case there exists an IK solution but the planner fails to connect it to the start anyway due to clutter or weird kinematics.

**Comment by marioprats** [comment]
There are now two buttons that allow checking for collisions and IK
