### ISSUE TITLE
Benchmark motion planning start tree could not be initialized

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#83]
I have one planning scene with one goal. I have one robot and one start state defined for it. Inside the plugin I run the planner and get a path from the start state to the goal pose, but when running it through the benchmark I get the following error:

[DEBUG] [1355278041.939472148]: Calling OMPL:RRTConnectkConfigDefault
[ WARN] [1355278041.947116776]: It looks like the planning volume was not specified.
[ INFO] [1355278041.952691085]: Planner configuration 'arm[RRTConnectkConfigDefault]' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[DEBUG] [1355278041.960540989]: searchPositionIK2: Position request pose is 0.337648 -0.327771 0.541509 -0.701566 -0.0155512 -0.0157234 0.712261
[DEBUG] [1355278041.960721688]: Iteration: 0, time: 0.000172, Timeout: 0.500000
[DEBUG] [1355278041.978189117]: Could not find IK solution
[DEBUG] [1355278041.978302855]: Iteration: 1, time: 0.017811, Timeout: 0.500000
[ WARN] [1355278041.985602084]: Skipping invalid start state (invalid state)
[ERROR] [1355278041.985722372]: Motion planning start tree could not be initialized!
[ INFO] [1355278041.985759617]: No solution found after 0.031908 seconds
[DEBUG] [1355278041.995595079]: Could not find IK solution
[DEBUG] [1355278041.995649298]: Iteration: 2, time: 0.035162, Timeout: 0.500000
[DEBUG] [1355278042.011995601]: Could not find IK solution
[DEBUG] [1355278042.012083151]: Iteration: 3, time: 0.051596, Timeout: 0.500000
[DEBUG] [1355278042.022212290]: Solved after 4 iterations
[ INFO] [1355278042.023372315]: Unable to solve the planning problem
[DEBUG] [1355278042.023495580]: Spent 0.000018 seconds collecting metrics

The planner is the same I used inside the plugin. Tried with others with the same result. Also tried different start states. Inside the rviz plugin, using the same start configuration, it works. Seems robot-specific, since I didn't get this error with another robot

**Comment by isucan** [comment]
Can you reset your start states db ? (using the new button that was added yesterday) and add the start state again? If that does not work, please send me the db

**Comment by marioprats** [comment]
That did the trick! thx!

**Comment by marioprats** [comment]
Actually it didn't solve the problem :(
Seems to work fine if the scene was defined for the same robot, but fails if not
