### ISSUE TITLE
Feature Request: Add marker size parameter to InteractionHandler class

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#89]
Found in file:
https://github.com/ros-planning/moveit-ros/blob/groovy-devel/planning_interface/robot_interaction/src/robot_interaction.cpp

I would like to add a "marker_size" parameter to the InteractionHandler class.

By default marker_size is 0 but, if specified, it will override the end effector size that is used to determine the scale of the generated interactive marker.

This size change will then occur in function
void RobotInteraction::addInteractiveMarkers(const InteractionHandlerPtr &handler) 
in file 
moveit_ros/planning_interface/robot_interaction/src/robot_interaction.cpp

Just requesting that @isucan verify that it is ok that I make this change

**Comment by isucan** [comment]
InteractionHandler should not know about the marker size, so I propose doing things differently:

In this function

```
void RobotInteraction::decideActiveComponents(const std::string &group)
```

(and the two other decision functions it calls)
pass an optional argument:

```
void RobotInteraction::decideActiveComponents(const std::string &group,
          const std::map<std::string, double> &group_scales = std::map<std::string, double>());
```

Then internally, instead of always calling computeGroupScale, call that function only if no scale has been specified in the map.

**Comment by davetcoleman** [comment]
Thanks, but I ended up doing it differently than both these suggestions. I think my solution is simpler and your suggestion didn't address the exact issue I needed to solve in the motion planning plugin because of the way I had asked the question. 

Pull request is [here](https://github.com/ros-planning/moveit-ros/pull/90)

**Comment by isucan** [comment]
I like your proposed solution. The only request I have is to change the parameter from a double to a std::map<std::string, double> and use that instead of a fixed value.
