### ISSUE TITLE
Draw the approach direction for a goal instead of a frame

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#95]
Only gripper X (normal to palm) and Y (fingertip-to-fingertip direction) should be shown. We usually draw X long (since that's the grasp direction) and Y short (just to give a sense of which direction the fingertips are oriented)

**Comment by marioprats** [comment]
cc @KaijenHsiao 
Since we cannot assume a given axis is the forward direction for the gripper (different robots may use different axis), and the srdf does not seem to include this information (@isucan ?), for now I have included three checkboxes in the ui that let the user select which axis to display on the goal poses. Please re-open it if you think there is a better solution.

Implemented in 753ffd75c34f29768194db23ed0f344a630c1463

**Comment by isucan** [comment]
@mateiciocarlie @marioprats would you like to add additional information to the end_effector tag of the SRDF?

**Comment by mateiciocarlie** [comment]
Right, this was part of an old (2011) discussion on SRDFs captured here:

https://home.willowgarage.com/wgwiki/SRDF

I think at the time we decided against capturing things like "default approach direction for grasping" in and end-effector SRDF, but now we again find we need that information _somewhere_. The manipulation pipeline has it in a .yaml file. I would be happy putting it into the SRDF.

**Comment by isucan** [comment]
we can have a default approach vector specified as an optional attribute. Would something like default_approach="x y z" do?

**Comment by marioprats** [comment]
That would be helpful in my opinion, specially for grasping
