### ISSUE TITLE
Change eef color to indicate collision when moving goal poses

### ISSUE THREAD

**Issue by adamantivm** [moveit/moveit_ros#97]
Sometimes it is very difficult to see if a goal pose will make the end effector be in collision with the scene.
It would be very helpful if the end effector which is shown when moving around a goal turned a different color (red?) when it is in collision with a scene object

**Comment by adamantivm** [comment]
Currently I find myself spending a huge amount of time moving around crowded scenes to make sure eef are not in collision for new poses. This feature would accelerate this process considerably.

**Comment by mateiciocarlie** [comment]
Agreed, this feature would be very useful. We have discussed it in a separate ticket (which one was it?) last week I think. @marioprats @isucan - any thoughts?

**Comment by marioprats** [comment]
Right, this would be very helpful. I'm considering this feature inside #78

**Comment by marioprats** [comment]
This should be ready. Collisions will be checked each time you finish dragging a goal pose, or when you click the Check Collisions button. The goal pose will switch to a yellow color if in collision
