### ISSUE TITLE
Add reachable flag to benchmark output

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#98]
If I'm not missing something, the benchmark output does not include the case where the goal is reachable and free of collision, even if the planner cannot solve for it. For the kinematic analysis we might need to know whether a goal can be reached or not, independently if the planner can solve the problem.

So, in addition to the current SOLVED field, I would suggest adding a REACHABLE and COLLISION_FREE field, the former to be true if the goal is inside the robot ws, and the latter set to true if, in addition, the robot can reach the goal without collisions. This seems to be computed somewhere, since it is printed on screen. How feasible is to bring that info to the higher layer and write it into the file?

**Comment by isucan** [comment]
I would like this to be a separate tool, not in the benchmarking. The goal representations we have for planning are implicit and do not necessarily require producing explicit states. This means that you can solve the planning problem without knowing a goal configuration a priori. This means that the feature you request should be done in a different fashion. I absolutely agree we need this functionality though and a tool that implements it would be simple.

**Comment by marioprats** [comment]
After discussing with @isucan, seems that the best solution is to create a separate tool more focused on benchmarking kinematic configurations, and then call the current benchmark tool for benchmarking a planner if we need to. So I'll close this ticket and create a create a new one for the new tool

**Comment by sachinchitta** [comment]
There is a tool for this in kinematics_reachability - it needs to be refactored and cleaned up but it does what you want.

**Comment by mateiciocarlie** [comment]
+1 to all said here: we do want this capability and this seems like the right way to have it.
