### ISSUE TITLE
Tool for benchmarking kinematic configurations

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#99]
We need a tool, build on top of moveit benchmarks, that is more specific to kinematic analysis.

So, in addition to the current SOLVED field provided by the current benchmark tool, I would suggest adding a REACHABLE and COLLISION_FREE field, the former to be true if the goal is inside the robot ws, and the latter set to true if, in addition, the robot can reach the goal without collisions. If the goal is reachable and collision-free, we could then benchmark planners with the existing tool.

**Comment by isucan** [comment]
+1

**Comment by isucan** [comment]
@marioprats If you would like to do this, we should chat about the design of this tool a bit, when you have time.

**Comment by marioprats** [comment]
After having a look to the code, one possibility I was considering is to
implement an analogous to run_benchmark.cpp (i.e.
run_kinematics_benchmark.cpp), the first one would be the current benchmark
tool for planners, and the second one would involve just IK. We can make a
superclass for both if needed, since methods like computeBenchmark would be
common (although specialized). For the calling part, benchmarks_config
could be refactored a bit so that everything can be reused for calling one
or the other. Currently it calls specifically the existing benchmark tool,
but most of the code (cfg file processing, loading from the warehouse..)
can be reused for the other case. What do you think?

**Comment by isucan** [comment]
Sounds good to me! I don't think we need a superclass for both. I think refactoring benchmarks_config as needed should be sufficient.

**Comment by mateiciocarlie** [comment]
+1. This would be great, and I think when it's done the kinematics_benchmark will be much quicker to run as well, giving us a quicker way to get feedback as we're dealing with various robot configurations.

**Comment by marioprats** [comment]
Finally I have refactored benchmark_config and call_benchmark so that the actual call to the benchmark service is done in the latter. This allows to reuse benchmark_config for parsing the config file both in the planner and the kinematic benchmark tool. How do you feel with that?

The kinematic benchmark server can then be executed as:

1) Running the server. You can duplicate the existing benchmark_server.launch, and call to the node moveit_run_kinematic_benchmark instead of moveit_run_benchmark
2) Running the client:
`rosrun moveit_ros_benchmarks moveit_call_kinematic_benchmark <config_file> --host <host> --port <port> [--include-planners]`

The output will be a file analogous to that generated by the planner benchmark, with the exception of the metrics, that in this case will be: reachable (bool), collision_free (bool) and time (float). The optional --include-planners parameter makes the kinematic benchmark call the planner benchmark if the goal is reachable and collision-free, but will not work until I get rid of the deserializing buffer overrun exception on the service call :( any ideas on that?

**Comment by isucan** [comment]
Minor changes to what Mario said:
i refactored the code a bit:
- I merged the two benchmark servers into one
- merged the two call_benchmark tools into one

The option --include-planners is not there, but two other options exist instead: --goal-existance-only and --planners-only
These options allow disabling some of the benchmarks. We still need to work a bit on how the goal existance works, but it should be fine for now.

**Comment by marioprats** [comment]
Great! thanks for the iteration Ioan!
